/**
 * Generates database/seed_election_government.sql from scraper/data/government.json: manifest key `government` (the
 * parties that formed the government after each VS election; spec 2026-10-07-seat-analysis-design.md §4.3).
 * Fill-only: sets the key where the published manifest (and a pending draft) has none, so admin edits win.
 * Usage: npx ts-node src/government-cli.ts
 */
import * as fs from 'fs';
import * as path from 'path';

export interface GovRow { state: string; year: number; parties: string[]; label?: string; source: string }

export function validate(rows: GovRow[]): void {
  const seen = new Set<string>();
  for (const r of rows) {
    const k = `${r.state} ${r.year}`;
    if (seen.has(k)) throw new Error(`duplicate ${k}`);
    seen.add(k);
    if (!r.parties?.length) throw new Error(`${k}: no parties`);
    if (!r.source) throw new Error(`${k}: no source`);
  }
}

const q = (s: string) => s.replace(/'/g, "''");

export function renderGovernmentSeed(rows: GovRow[]): string {
  validate(rows);
  const values = rows.map(r => `  ('${q(r.state)}', ${r.year}, '${q(JSON.stringify({ parties: r.parties, ...(r.label ? { label: r.label } : {}), source: r.source }))}'::jsonb)`).join(',\n');
  const from = `FROM (VALUES\n${values}\n) AS g(code, year, gov)\nJOIN states s ON s.code = g.code`;
  return `-- Generated by scraper/src/government-cli.ts from scraper/data/government.json. Do not edit by hand.
-- Manifest key "government": the parties that formed the government after each VS election (bellwether seats).
-- Fill-only: only where the manifest has no "government" key, so an admin's edit is never overwritten.
UPDATE elections e SET manifest_url = jsonb_set(e.manifest_url::jsonb, '{government}', g.gov)::text
${from}
WHERE e.state_id = s.id AND e.year = g.year AND e.type = 'VS' AND e.manifest_url IS NOT NULL
  AND NOT (e.manifest_url::jsonb ? 'government');

UPDATE elections e SET manifest_draft = jsonb_set(e.manifest_draft, '{government}', g.gov)
${from}
WHERE e.state_id = s.id AND e.year = g.year AND e.type = 'VS' AND e.manifest_draft IS NOT NULL
  AND NOT (e.manifest_draft ? 'government');
`;
}

if (require.main === module) {
  const rows = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../data/government.json'), 'utf8')) as GovRow[];
  fs.writeFileSync(path.resolve(__dirname, '../../database/seed_election_government.sql'), renderGovernmentSeed(rows));
  console.log(`${rows.length} elections`);
}
