/**
 * Hosted images (person photos): S3 bucket `S3_BUCKET` (public-read by bucket policy), served from `S3_PUBLIC_BASE_URL`.
 * Every upload also keeps a local copy under scraper/data/media/<key> (gitignored), so a change of host never needs the
 * sources again. Replaced Vercel Blob on 2026-10-05 (the Blob store was suspended); keys are unchanged.
 */
import * as fs from 'fs';
import * as path from 'path';
import { PutObjectCommand, S3Client } from '@aws-sdk/client-s3';

export const BLOB_BASE = /^https:\/\/[a-z0-9]+\.public\.blob\.vercel-storage\.com\//;
const CACHE = 'public, max-age=31536000, immutable';

export const s3UrlFor = (publicBase: string, key: string) => `${publicBase.replace(/\/+$/, '')}/${key}`;

/** The S3 URL of an image that was on Vercel Blob (same key); any other URL is returned unchanged. */
export const blobToS3 = (url: string, publicBase: string) => (BLOB_BASE.test(url) ? s3UrlFor(publicBase, url.replace(BLOB_BASE, '')) : url);

export interface MediaStore { put(key: string, body: Buffer, contentType: string): Promise<string> }

interface Opts {
  bucket: string; publicBase: string; localDir: string;
  /** Sends an S3 command (injected in tests). */
  send: (cmd: PutObjectCommand) => Promise<unknown>;
}

export function createMediaStore(o: Opts): MediaStore {
  return {
    async put(key, body, contentType) {
      const local = path.join(o.localDir, key);
      fs.mkdirSync(path.dirname(local), { recursive: true });
      fs.writeFileSync(local, body);
      await o.send(new PutObjectCommand({ Bucket: o.bucket, Key: key, Body: body, ContentType: contentType, CacheControl: CACHE }));
      return s3UrlFor(o.publicBase, key);
    },
  };
}

/** The store from the environment (S3_BUCKET, S3_REGION, S3_PUBLIC_BASE_URL, AWS keys); throws when unset. */
export function mediaStoreFromEnv(): MediaStore {
  const bucket = process.env.S3_BUCKET, region = process.env.S3_REGION, publicBase = process.env.S3_PUBLIC_BASE_URL;
  if (!bucket || !region || !publicBase) throw new Error('S3_BUCKET, S3_REGION and S3_PUBLIC_BASE_URL must be set (scraper/.env)');
  const client = new S3Client({ region });
  return createMediaStore({ bucket, publicBase, localDir: path.resolve(__dirname, '../data/media'), send: cmd => client.send(cmd) });
}

/**
 * seed_media_s3_v1.sql: production rows written by the (frozen) Bihar seeds and admin uploads hold Vercel Blob URLs;
 * the same keys now live on S3. Rewrites the host only where the Blob URL is still there, once (seed_runs).
 */
export function emitMediaRewriteSeed(blobBase: string, s3Base: string): string {
  const from = blobBase.replace(/\/+$/, ''), to = s3Base.replace(/\/+$/, '');
  const at = from.length + 1;
  const like = `'${from}/%'`;
  const col = (table: string, c: string) => `UPDATE ${table} SET ${c} = '${to}' || substr(${c}, ${at}) WHERE ${c} LIKE ${like};`;
  return [
    'BEGIN;', '',
    '-- Run once (seed_runs). Images moved from Vercel Blob (store suspended 2026-10-04) to S3 under the same keys',
    '-- (scraper/src/bihar/media-migrate-cli.ts re-hosted them from their sources). Rewrites stored URLs still on the',
    '-- Blob host; a URL an admin changed since is left alone. Generated by scraper/src/media-rewrite-cli.ts.',
    "SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_media_s3_v1') AS seed_apply \\gset",
    '\\if :seed_apply', '',
    col('persons', 'photo_url'),
    col('parties', 'symbol_url'),
    col('parties', 'eci_symbol_url'),
    `UPDATE image_credits c SET url = '${to}' || substr(c.url, ${at}) WHERE c.url LIKE ${like}`,
    `  AND NOT EXISTS (SELECT 1 FROM image_credits d WHERE d.url = '${to}' || substr(c.url, ${at}));`,
    '', '\\endif',
    "INSERT INTO seed_runs (name) VALUES ('seed_media_s3_v1') ON CONFLICT (name) DO NOTHING;", '',
    'COMMIT;', '',
  ].join('\n');
}
