/**
 * Seeds for the party model (migration 023, spec docs/superpowers/specs/2026-10-06-party-model-design.md §6):
 * - seed_party_lineage.sql — renames, mergers, splits (fill-only, curated in scraper/data/parties/lineage.json);
 * - seed_party_units_v1.sql / _v2.sql — state units and their leaders (run-once: admins will edit units later), from
 *   scraper/data/parties/units-1..4.json (v1) and units-5.json (v2: Sikkim); see unitsSeedOf. A leader is linked to a person through a matching candidacy's person
 *   (candidate ids are stable across databases; person ids are not).
 */
import { q } from './bihar/sql';
import { runOnce } from './seed-run-once';

export interface LineageRow {
  party_id: string; predecessor_id: string; kind: string; effective_date: string; state_code: string | null;
  is_successor: boolean; note: string | null; source_url: string | null;
}
export interface UnitRole { role: string; person_name: string; from_date: string | null; to_date: string | null; source_url: string | null;
  /** The person's name on a ballot when it differs from person_name (matched exactly). */ ballot_name?: string;
  /** Never contested an assembly election here: no link (a relative's ballot may contain the same words). */ no_candidacy?: boolean }
export interface UnitRow { party_id: string; state_code: string; eci_recognition: string | null; office: string | null; website: string | null; roles: UnitRole[] }

const KINDS = new Set(['rename', 'merger', 'split', 'breakaway']);
const ROLES = new Set(['state_president', 'legislature_leader']);
const RECOGNITION = new Set(['National', 'State', 'Unrecognised']);

function party(id: string, parties: Set<string>): string {
  if (!parties.has(id)) throw new Error(`unknown party ${id}`);
  return id;
}
function state(code: string | null, states: Map<string, number>): number | null {
  if (code === null) return null;
  const id = states.get(code);
  if (id === undefined) throw new Error(`unknown state ${code}`);
  return id;
}

export function emitLineageSeed(rows: LineageRow[], parties: Set<string>, states: Map<string, number>): string {
  const lines = rows.map(r => {
    if (!KINDS.has(r.kind)) throw new Error(`bad kind ${r.kind}`);
    const values = [q(party(r.party_id, parties)), q(party(r.predecessor_id, parties)), q(r.kind), q(r.effective_date), q(state(r.state_code, states)), String(r.is_successor), q(r.note), q(r.source_url)];
    return `INSERT INTO party_lineage (party_id, predecessor_id, kind, effective_date, state_id, is_successor, note, source_url) VALUES (${values.join(', ')}) ON CONFLICT DO NOTHING;`;
  });
  return [
    '-- Party lineage: renames, mergers and splits that cross-election comparisons follow (migration 023). Generated by',
    '-- scraper/src/party-model-cli.ts from the sourced scraper/data/parties/lineage.json. Fill-only, idempotent.',
    '',
    ...lines,
    '',
  ].join('\n');
}

const words = (n: string) => n.toUpperCase().replace(/[^A-Z ]/g, ' ').split(/\s+/).filter(Boolean);

/**
 * The candidacy (newest) that is this person: every word of the name, initials included (M. Veerapandian is not
 * K. Veerapandian), appears in the ballot name, and the candidacy is for the unit's party or a party related to it by
 * lineage. Null when none matches or the matches are two different ballot names (ambiguous).
 */
export function pickCandidate(cands: { id: string; name: string; year: number; party: string }[], personName: string,
  partyId: string, related: (party: string) => boolean = () => false, ballotName?: string): string | null {
  if (ballotName) {
    // The exact ballot name (Telugu names change order and initials: "Chandrababu Naidu Nara"), newest candidacy.
    const exact = cands.filter(c => (c.party === partyId || related(c.party)) && c.name.toUpperCase() === ballotName.toUpperCase());
    return exact.length ? [...exact].sort((a, b) => b.year - a.year)[0].id : null;
  }
  const want = words(personName);
  if (!want.some(w => w.length > 1)) return null;
  const hits = cands.filter(c => {
    if (c.party !== partyId && !related(c.party)) return false;
    const w = new Set(words(c.name)); return want.every(x => w.has(x));
  });
  if (!hits.length || new Set(hits.map(h => h.name.toUpperCase())).size > 1) return null;
  return [...hits].sort((a, b) => b.year - a.year)[0].id;
}

/**
 * The run-once seed a units file belongs to. Shipped seeds are frozen and their markers already set on production, so
 * every new units file needs its own version here (add `units-6.json` → v3, …); an unmapped file is an error.
 */
const UNITS_SEEDS: [RegExp, string][] = [[/^units-[1-4]\.json$/, 'seed_party_units_v1'], [/^units-5\.json$/, 'seed_party_units_v2'], [/^units-6\.json$/, 'seed_party_units_v3'], [/^units-7\.json$/, 'seed_party_units_v4'], [/^units-8\.json$/, 'seed_party_units_v5']];
export function unitsSeedOf(file: string): string {
  const hit = UNITS_SEEDS.find(([re]) => re.test(file));
  if (!hit) throw new Error(`${file} has no seed version: add it to UNITS_SEEDS with a new run-once seed (v1/v2 are frozen)`);
  return hit[1];
}

export function emitUnitsSeed(units: UnitRow[], parties: Set<string>, states: Map<string, number>,
  candidateFor: (personName: string, stateCode: string, partyId: string, ballotName?: string) => string | null, name = 'seed_party_units_v1'): string {
  const body: string[] = [];
  for (const u of units) {
    const p = party(u.party_id, parties);
    const s = state(u.state_code, states)!;
    if (u.eci_recognition !== null && !RECOGNITION.has(u.eci_recognition)) throw new Error(`bad recognition ${u.eci_recognition}`);
    body.push(`INSERT INTO party_units (party_id, state_id, eci_recognition, office, website) VALUES (${q(p)}, ${s}, ${q(u.eci_recognition)}, ${q(u.office)}, ${q(u.website)}) ON CONFLICT DO NOTHING;`);
    for (const role of ROLES) {
      const open = u.roles.filter(r => r.role === role && !r.to_date).length;
      if (open > 1) throw new Error(`${u.party_id} ${u.state_code} ${role} has ${open} current holders`);
    }
    for (const r of u.roles) {
      if (!ROLES.has(r.role)) throw new Error(`bad role ${r.role}`);
      if (!r.person_name) throw new Error(`${u.party_id} ${u.state_code} ${r.role} has no person_name`);
      const cand = r.no_candidacy ? null : candidateFor(r.person_name, u.state_code, p, r.ballot_name);
      const person = cand ? `(SELECT person_id FROM candidates WHERE id = ${q(cand)})` : 'NULL';
      body.push(`INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES (${q(p)}, ${s}, ${q(r.role)}, ${person}, ${q(r.person_name)}, ${q(r.from_date)}, ${q(r.to_date)}, ${q(r.source_url)}) ON CONFLICT DO NOTHING;`);
    }
  }
  return runOnce({
    name,
    comment: [
      'Party state units and their leaders (migration 023). Run once: admins will edit units later. Generated by',
      'scraper/src/party-model-cli.ts from the sourced scraper/data/parties/units-*.json (user-approved).',
    ],
    body,
  }).join('\n');
}
