/**
 * Generate SQL to set state_id + region_id on persons based on their constituency.
 *
 * Reads bihar-person-matches.json, extracts constituency number from each group,
 * maps to a region code via bihar-region-map, and emits UPDATE statements.
 *
 * Usage: npx ts-node src/seed-person-regions.ts
 * Output: ../database/seed_bihar_person_regions.sql
 */
import * as fs from 'fs';
import * as path from 'path';
import { biharRegionMap } from './bihar-region-map';

interface Candidate {
  id: string;
  name: string;
  person_id: string | null;
}

interface PersonGroup {
  normalized_name: string;
  constituency: string; // e.g. "95_KANTI"
  elections_count: number;
  confidence: 'high' | 'medium' | 'review';
  candidates: Candidate[];
}

interface Report {
  summary: Record<string, unknown>;
  persons: PersonGroup[];
}

const BIHAR_STATE_ID = 5;

const INPUT = path.join(__dirname, '..', 'output', 'bihar-person-matches.json');
const OUTPUT = path.join(__dirname, '..', '..', 'database', 'seed_bihar_person_regions.sql');

// Also read the generated persons seed to get person IDs
const PERSONS_SEED = path.join(__dirname, '..', '..', 'database', 'seed_bihar_persons.sql');

const report: Report = JSON.parse(fs.readFileSync(INPUT, 'utf-8'));

// Filter to high + medium (same filter as seed-person-matches.ts)
const groups = report.persons.filter(g => g.confidence !== 'review');

// Build a map of candidate_id → person_id from the seed SQL
// Parse lines like: UPDATE candidates SET person_id = 'UUID' WHERE id IN ('id1', 'id2', ...);
const personSeedSql = fs.readFileSync(PERSONS_SEED, 'utf-8');
const candidateToPersonId = new Map<string, string>();
const insertPersonIds = new Set<string>();

for (const line of personSeedSql.split('\n')) {
  // Match INSERT INTO persons
  const insertMatch = line.match(/INSERT INTO persons \(id, name\) VALUES \('([^']+)'/);
  if (insertMatch) {
    insertPersonIds.add(insertMatch[1]);
  }
  // Match UPDATE candidates SET person_id
  const updateMatch = line.match(/UPDATE candidates SET person_id = '([^']+)' WHERE id IN \(([^)]+)\)/);
  if (updateMatch) {
    const personId = updateMatch[1];
    const ids = updateMatch[2].match(/'([^']+)'/g)?.map(s => s.replace(/'/g, '')) || [];
    for (const cid of ids) {
      candidateToPersonId.set(cid, personId);
    }
  }
}

// Region code → region row ID (we'll use a subquery since IDs are auto-generated)
// But for efficiency, generate a CTE or use variables
// Simpler: just use subselect (SELECT id FROM regions WHERE state_id=5 AND code='...')

const updates: string[] = [];
let tagged = 0;
let skipped = 0;

for (const group of groups) {
  // Extract constituency number from format "95_KANTI"
  const constMatch = group.constituency.match(/^(\d+)_/);
  if (!constMatch) {
    skipped++;
    continue;
  }
  const constNo = parseInt(constMatch[1], 10);
  const regionCode = biharRegionMap[constNo];
  if (!regionCode) {
    skipped++;
    continue;
  }

  // Find person_id for this group: check if any candidate has a person_id in our map
  let personId: string | null = null;
  // First check if any candidate in the group already had a person_id in the JSON
  for (const c of group.candidates) {
    if (c.person_id) {
      personId = c.person_id;
      break;
    }
  }
  // If not, look up from the generated seed SQL
  if (!personId) {
    for (const c of group.candidates) {
      const pid = candidateToPersonId.get(c.id);
      if (pid) {
        personId = pid;
        break;
      }
    }
  }

  if (!personId) {
    skipped++;
    continue;
  }

  updates.push(
    `UPDATE persons SET state_id = ${BIHAR_STATE_ID}, region_id = (SELECT id FROM regions WHERE state_id = ${BIHAR_STATE_ID} AND code = '${regionCode}') WHERE id = '${personId}';`
  );
  tagged++;
}

const sql = [
  '-- Auto-generated by seed-person-regions.ts',
  `-- ${tagged} persons tagged with state_id=${BIHAR_STATE_ID} + region_id, ${skipped} skipped`,
  '',
  'BEGIN;',
  '',
  ...updates,
  '',
  'COMMIT;',
  '',
].join('\n');

fs.writeFileSync(OUTPUT, sql, 'utf-8');

console.log(`Written: ${OUTPUT}`);
console.log(`  Tagged: ${tagged}`);
console.log(`  Skipped: ${skipped}`);
