/**
 * Generate SQL seed file from bihar-person-matches.json analysis report.
 *
 * - Creates `persons` rows for high/medium confidence groups
 * - Reuses existing person_id where candidates already have one
 * - Sets person_id on all matched candidates
 *
 * The output is run-once (seed-run-once.ts): it never re-applies over admin merges, splits or person changes.
 * Regenerating mints new person ids for groups without one, so do it only for a fresh dataset.
 *
 * Usage: npx ts-node src/seed-person-matches.ts
 * Output: ../database/seed_bihar_persons.sql
 */
import * as fs from 'fs';
import * as path from 'path';
import { randomUUID } from 'crypto';
import { idsCte, NOT_IN_MERGE_LOG, runOnce } from './seed-run-once';

interface Candidate {
  id: string;
  name: string;
  person_id: string | null;
}

interface PersonGroup {
  normalized_name: string;
  constituency: string;
  elections_count: number;
  confidence: 'high' | 'medium' | 'review';
  candidates: Candidate[];
}

interface Report {
  summary: Record<string, unknown>;
  persons: PersonGroup[];
}

const INPUT = path.join(__dirname, '..', 'output', 'bihar-person-matches.json');
const OUTPUT = path.join(__dirname, '..', '..', 'database', 'seed_bihar_persons.sql');

const report: Report = JSON.parse(fs.readFileSync(INPUT, 'utf-8'));

const groups = report.persons.filter(g => g.confidence !== 'review');

const personInserts: string[] = [];
const candidateUpdates: string[] = [];
const personIds: string[] = [];
let newPersons = 0;
let reusedPersons = 0;
let totalCandidates = 0;

for (const group of groups) {
  // Check if any candidate already has a person_id
  const existingPersonId = group.candidates.find(c => c.person_id)?.person_id;

  const personId = existingPersonId ?? randomUUID();

  if (existingPersonId) {
    reusedPersons++;
  } else {
    newPersons++;
  }
  // Always emit the person row (idempotent): a "reused" person exists only in the DB the
  // report was generated from, so a fresh DB built from seeds would otherwise violate the FK.
  personIds.push(personId);
  const escapedName = group.normalized_name.replace(/'/g, "''");
  personInserts.push(
    `INSERT INTO persons (id, name) VALUES ('${personId}', '${escapedName}') ON CONFLICT (id) DO NOTHING;`
  );

  const candidateIds = group.candidates.map(c => `'${c.id}'`).join(', ');
  candidateUpdates.push(
    `UPDATE candidates SET person_id = '${personId}' WHERE id IN (${candidateIds});`
  );
  totalCandidates += group.candidates.length;
}

const PERSONS_RUN_ONCE_COMMENT = [
  'Run once (seed_runs, migration 018). setup.sh re-runs every seed; re-applying these links would undo',
  'admin merges, splits and person changes, and the orphan trigger would delete the persons admins chose.',
  'The body runs only when this file has no seed_runs row and none of its person ids exists in persons or',
  'appears in person_merges (a database where an older setup.sh already applied it). Marked either way.',
];

const sql = [
  '-- Auto-generated by seed-person-matches.ts',
  `-- ${groups.length} groups (${newPersons} new persons, ${reusedPersons} reused), ${totalCandidates} candidates`,
  '-- Confidence: high + medium only (review excluded)',
  '',
  ...runOnce({
    name: 'seed_bihar_persons',
    comment: PERSONS_RUN_ONCE_COMMENT,
    cte: idsCte(personIds),
    conditions: ['NOT EXISTS (SELECT 1 FROM persons p JOIN ids USING (id))', NOT_IN_MERGE_LOG],
    body: ['-- Create persons', ...personInserts, '', '-- Link candidates to persons', ...candidateUpdates],
  }),
].join('\n');

fs.writeFileSync(OUTPUT, sql, 'utf-8');

console.log(`Written: ${OUTPUT}`);
console.log(`  Groups: ${groups.length}`);
console.log(`  New persons: ${newPersons}`);
console.log(`  Reused persons: ${reusedPersons}`);
console.log(`  Candidates linked: ${totalCandidates}`);
