-- Manipur parties: every party that fielded a Manipur VS candidate 2012-2022 (generated by scraper/src/bihar/generate-cli.ts).
-- Fill-only: existing rows (and admin edits) are never changed. Runs before the Manipur corrections and VS seeds.

INSERT INTO parties (id, name, abbreviation, color, eci_recognition) VALUES
  ('AIFB', 'All India Forward Bloc', NULL, '#808080', NULL),
  ('BJP', 'Bharatiya Janata Party', NULL, '#FF7A1A', 'National'),
  ('CPI', 'Communist Party of India', NULL, '#FF0000', NULL),
  ('CPIM', 'Communist Party of India  (Marxist)', NULL, '#B83A3E', 'National'),
  ('INC', 'Indian National Congress', NULL, '#38C6F4', 'National'),
  ('IVD', 'Inqalab Vikas Dal', 'IVD', '#9CA3AF', 'Unrecognised'),
  ('JDS', 'Janata Dal  (Secular)', NULL, '#228B22', NULL),
  ('JDU', 'Janata Dal  (United)', 'JD(U)', '#1FA37A', 'State'),
  ('JMBP', 'Jai Maha Bharath Party', NULL, '#808080', NULL),
  ('KNA', 'Kuki National Assembly', 'KNA', '#9CA3AF', 'Unrecognised'),
  ('KPA', 'Kuki People’s Alliance', 'KPA', '#9CA3AF', 'Unrecognised'),
  ('LJP', 'Lok Janshakti Party', NULL, '#0000CD', NULL),
  ('LJPRV', 'Lok Janshakti Party(Ram Vilas)', NULL, '#3B8BFF', NULL),
  ('MDPF', 'Manipur Democratic Peoples''s Front', 'MDPF', '#9CA3AF', 'Unrecognised'),
  ('MNDF', 'Manipur National Democratic Front', 'MNDF', '#9CA3AF', 'Unrecognised'),
  ('MPP', 'Manipur Peoples Party', 'MPP', '#9CA3AF', 'State'),
  ('MSCP', 'Manipur State Congress Party', 'MSCP', '#9CA3AF', 'Unrecognised'),
  ('NCP', 'Nationalist Congress Party', NULL, '#006699', NULL),
  ('NEINDP', 'North East India Development Party', 'NEINDP', '#9CA3AF', 'Unrecognised'),
  ('NPF', 'Naga Peoples Front', NULL, '#556B2F', NULL),
  ('NPP', 'National People''s Party', NULL, '#808080', 'National'),
  ('PDA', 'People''s Democratic Alliance', 'PDA', '#9CA3AF', 'State'),
  ('PRJA', 'Peoples Resurgence and Justice Alliance', 'PRJA', '#9CA3AF', 'Unrecognised'),
  ('RJSNP', 'Rashtriya Janhit Sangharsh Party', 'RJSNP', '#9CA3AF', 'Unrecognised'),
  ('RPOI2', 'Republican Party of India (Athawale)', NULL, '#808080', NULL),
  ('RPOIA', 'Republican Party of India (A)', NULL, '#808080', NULL),
  ('SDPOI', 'Social Democratic Party Of India', NULL, '#808080', NULL),
  ('SHS', 'Shiv Sena', NULL, '#FF6600', NULL),
  ('TMC', 'All India Trinamool Congress', NULL, '#00CC44', NULL)
ON CONFLICT (id) DO NOTHING;
