BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/eci/INLD.svg', 'https://commons.wikimedia.org/wiki/File:INLD1.svg', 'Khushank94 (original), Furfur (vector)', 'Public domain'),
  ('/symbols/logos/JJP2.jpg', 'https://commons.wikimedia.org/wiki/File:Jananayak_Janata_Party_logo.jpg', 'LakhnawiNawab', 'CC BY 4.0'),
  ('/symbols/eci/JJP2.svg', 'https://commons.wikimedia.org/wiki/File:Indian_election_symbol_Key.svg', '√Tæ√', 'FAL'),
  ('/symbols/logos/ASPKR.webp', 'https://commons.wikimedia.org/wiki/File:AZAD_SAMAJ_PARTY_LOGO.webp', 'MY Gohad', 'CC BY-SA 4.0'),
  ('/symbols/eci/ASPKR.jpg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Kettle.jpg', 'Election Commission of India', 'CC BY-SA 4.0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Haryana 2024 top parties, researched with sources (scraper/data/hr/
-- parties-2024.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_hr_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'INLD'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1996),
  leader_name = COALESCE(leader_name, 'Om Prakash Chautala'),
  headquarters = COALESCE(headquarters, 'MLA Flat No. 47, Sector 4, Chandigarh 160004'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Indian_National_Lok_Dal'),
  description = COALESCE(description, 'A Haryana regional party founded by Devi Lal in 1996 and led by the Chautala family, which governed the state several times. In 2024 it fought in alliance with the BSP and won 2 of 90 seats (Dabwali and Rania) with about 4.1% of the vote.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#005747' ELSE color END
WHERE id = 'INLD';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'JJP'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2018),
  leader_name = COALESCE(leader_name, 'Ajay Singh Chautala'),
  headquarters = COALESCE(headquarters, '18, Janpath, New Delhi'),
  website = COALESCE(website, 'http://www.jannayakjantaparty.com/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Jannayak_Janta_Party'),
  description = COALESCE(description, 'A Haryana party formed in 2018 by Ajay Singh Chautala and his son Dushyant Chautala after a split in the INLD; it shared power with the BJP from 2019 to March 2024. Allied with the Azad Samaj Party in 2024, it won none of the 66 seats it contested and about 0.9% of the vote.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#71B218' ELSE color END
WHERE id = 'JJP2';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'ASP(KR)'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2020),
  leader_name = COALESCE(leader_name, 'Chandrashekhar Azad'),
  headquarters = COALESCE(headquarters, '3/22-C-136, C Block, Gokulpur, New Delhi 110094'),
  website = COALESCE(website, 'https://aazadsamajpartyk.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Aazad_Samaj_Party_(Kanshi_Ram)'),
  description = COALESCE(description, 'An Ambedkarite party founded in 2020 by Bhim Army leader Chandrashekhar Azad, based mainly in Uttar Pradesh. In Haryana in 2024 it contested 12 seats in alliance with the JJP and won none, with about 0.1% of the vote.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#030F89' ELSE color END
WHERE id = 'ASPKR';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_hr_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

