BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/eci/DMDK.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Nagara.svg', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/eci/AMMK.png', 'https://commons.wikimedia.org/wiki/File:AMMK_SYMBOL_PRESSURE_COOKER.png', 'Thiyagu Ganesh', 'CC0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Tamil Nadu 2026 top parties, researched with sources (scraper/data/tn/
-- parties-2026.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_tn_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'DMDK'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2005),
  leader_name = COALESCE(leader_name, 'Premallatha Vijayakant'),
  headquarters = COALESCE(headquarters, 'Chennai, Tamil Nadu'),
  website = COALESCE(website, 'https://dmdkparty.com/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Desiya_Murpokku_Dravida_Kazhagam'),
  description = COALESCE(description, 'A party founded by actor Vijayakant in 2005 and led since his death by his wife Premalatha. It joined the DMK-led alliance for 2026 and won one of its ten seats.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FFD700' ELSE color END
WHERE id = 'DMDK';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AMMK'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2018),
  leader_name = COALESCE(leader_name, 'T. T. V. Dhinakaran'),
  headquarters = COALESCE(headquarters, 'Chennai, Tamil Nadu'),
  website = COALESCE(website, 'http://www.ammk.com/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Amma_Makkal_Munnetra_Kazhagam'),
  description = COALESCE(description, 'A breakaway from the AIADMK launched by T. T. V. Dhinakaran in 2018. It rejoined the AIADMK-led alliance for 2026 and won one of its 11 seats.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#006633' ELSE color END
WHERE id = 'AMMK';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_tn_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

