BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/eci/SKM.png', 'https://commons.wikimedia.org/wiki/File:Symbol_SKM.png', 'Reetban', 'CC BY-SA 4.0'),
  ('/symbols/eci/SDF.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Umberlla.png', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/eci/CAP1.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Nagrik.png', 'XYZ 250706', 'CC BY-SA 4.0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Sikkim 2024 top parties, researched with sources (scraper/data/sk/
-- parties-2024.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_sk_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'SKM'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2013),
  leader_name = COALESCE(leader_name, 'Prem Singh Tamang'),
  headquarters = COALESCE(headquarters, 'Ghaley Compound, Tibet Road, Gangtok 737101, Sikkim'),
  website = COALESCE(website, 'https://www.sikkimkrantikarimorcha.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Sikkim_Krantikari_Morcha'),
  description = COALESCE(description, 'A Sikkim regional party founded on 4 February 2013 at Soreng by P. S. Golay (Prem Singh Tamang), a former SDF minister who had broken with Pawan Chamling; it has governed Sikkim since 2019 with Golay as Chief Minister. In 2024 it won 31 of 32 seats with about 58.4% of the vote, and the lone opposition MLA joined it in July 2024.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#ED1E26' ELSE color END
WHERE id = 'SKM';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'SDF'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1993),
  leader_name = COALESCE(leader_name, 'Pawan Kumar Chamling'),
  headquarters = COALESCE(headquarters, 'S.D.F. Bhawan, Indira Bypass, Gangtok, Sikkim'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Sikkim_Democratic_Front'),
  description = COALESCE(description, 'A Sikkim regional party founded in 1993 by Pawan Kumar Chamling, which governed the state from 1994 to 2019 with Chamling as Chief Minister for 25 years. In 2024 it won 1 of 32 seats with about 27.4% of the vote; Chamling lost both seats he contested, and the party''s only MLA joined the SKM in July 2024.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FBEC5D' ELSE color END
WHERE id = 'SDF';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'CAP'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2023),
  leader_name = COALESCE(leader_name, 'Ganesh Kumar Rai'),
  headquarters = COALESCE(headquarters, 'Adampool, near Gangtok, Sikkim'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Citizen_Action_Party_%E2%80%93_Sikkim'),
  description = COALESCE(description, 'A Sikkim regional party formed in January 2023 at Melli out of a reform campaign led by Ganesh Kumar Rai, presenting itself as reform-focused and crowd-funded. In its first assembly election, in 2024, it won no seats with about 6.0% of the vote, while its Lok Sabha candidate Bharat Basnett came second with about 21.7%.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#7B3FA0' ELSE color END
WHERE id = 'CAP1';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_sk_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

