BEGIN;

-- Party state units and their leaders (migration 023). Run once: admins will edit units later. Generated by
-- scraper/src/party-model-cli.ts from the sourced scraper/data/parties/units-*.json (user-approved).
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_party_units_v6')
   AS seed_apply \gset
\if :seed_apply

INSERT INTO party_units (party_id, state_id, eci_recognition, office, website) VALUES ('BJP', 13, 'National', 'Dr. Shyama Prasad Mookherjee Bhawan, Sector 3 Extension, Trikuta Nagar, Jammu 180012', 'https://jkbjp.in') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('BJP', 13, 'state_president', NULL, 'Sat Paul Sharma', '2024-11-03', NULL, 'https://www.thehindu.com/news/national/jammu-and-kashmir/sat-sharma-appointed-j-k-bjp-president/article68825007.ece') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('BJP', 13, 'state_president', (SELECT person_id FROM candidates WHERE id = 'd6b50bed-d4d7-5b8d-a42f-ffda17a0d8a8'), 'Ravinder Raina', '2018-05-13', '2024-11-03', 'https://indianexpress.com/article/india/bjp-mla-ravinder-raina-appointed-new-jammu-kashmir-unit-chief-5174998/') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('BJP', 13, 'legislature_leader', (SELECT person_id FROM candidates WHERE id = 'a0cc6829-a3a3-53c1-af8f-1e02d25af192'), 'Sunil Kumar Sharma', '2024-11-03', NULL, 'https://newsonair.gov.in/sunil-sharma-elected-leader-of-opposition-in-jammu-and-kashmir-assembly/') ON CONFLICT DO NOTHING;
INSERT INTO party_units (party_id, state_id, eci_recognition, office, website) VALUES ('INC', 13, 'National', 'Shaheedi Chowk, Jammu 180001', NULL) ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('INC', 13, 'state_president', (SELECT person_id FROM candidates WHERE id = '55a4422e-c6e3-560e-b975-34e73ec1fde4'), 'Tariq Hameed Karra', '2024-08-16', NULL, 'https://economictimes.indiatimes.com/news/elections/assembly-elections/jammu-kashmir/congress-appoints-tariq-hameed-karra-as-jammu-kashmir-congress-chief-ahead-of-assembly-elections/articleshow/112573994.cms') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('INC', 13, 'legislature_leader', (SELECT person_id FROM candidates WHERE id = 'daa84ba5-d1c4-5a51-a216-549eb4841656'), 'Ghulam Ahmad Mir', '2024-10-15', NULL, 'https://kashmirlife.net/g-a-mir-is-new-leader-of-congress-legislature-party-of-jk-369575/') ON CONFLICT DO NOTHING;
INSERT INTO party_units (party_id, state_id, eci_recognition, office, website) VALUES ('JKNC', 13, 'State', 'Nawa-e-Subha, Srinagar, Jammu and Kashmir', 'https://jknc.co.in') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('JKNC', 13, 'state_president', NULL, 'Farooq Abdullah', NULL, NULL, 'https://en.wikipedia.org/wiki/Jammu_%26_Kashmir_National_Conference') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('JKNC', 13, 'legislature_leader', (SELECT person_id FROM candidates WHERE id = '6aa409ad-ac8a-5a22-8c9f-a9e15efcf78f'), 'Omar Abdullah', '2024-10-10', NULL, 'https://newsonair.gov.in/omar-abdullah-unanimously-elected-as-legislature-party-leader-in-jk/') ON CONFLICT DO NOTHING;
INSERT INTO party_units (party_id, state_id, eci_recognition, office, website) VALUES ('JKPDP', 13, 'State', '2, Circuit House, Emporium Lane, Residency Road, Srinagar, Jammu and Kashmir', 'https://jkpdp.org') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('JKPDP', 13, 'state_president', NULL, 'Mehbooba Mufti', NULL, NULL, 'https://en.wikipedia.org/wiki/Jammu_and_Kashmir_Peoples_Democratic_Party') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('JKPDP', 13, 'legislature_leader', (SELECT person_id FROM candidates WHERE id = '5733ad0c-3cd7-57df-b837-688714e033de'), 'Waheed Para', '2024-11-14', NULL, 'https://www.greaterkashmir.com/jammu-kashmir/pdp-appoints-dr-mehboob-beg-as-partys-chief-spokesperson/') ON CONFLICT DO NOTHING;
INSERT INTO party_units (party_id, state_id, eci_recognition, office, website) VALUES ('JKPC', 13, 'Unrecognised', 'J-65, Jawahar Nagar, Srinagar, Jammu and Kashmir 190008', 'https://jkpcofficial.org') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('JKPC', 13, 'state_president', (SELECT person_id FROM candidates WHERE id = 'd30d6bdf-3904-51ab-8e34-3194ca49bf53'), 'Sajad Gani Lone', NULL, NULL, 'https://en.wikipedia.org/wiki/Jammu_and_Kashmir_People%27s_Conference') ON CONFLICT DO NOTHING;

\endif
INSERT INTO seed_runs (name) VALUES ('seed_party_units_v6') ON CONFLICT (name) DO NOTHING;

COMMIT;
