BEGIN;

-- Run once (seed_runs). Points the Assam manifests at the party ids the ECI data uses (a published manifest is
-- never rewritten by the year seeds). Generated by scraper/src/bihar/generate-cli.ts from
-- scraper/data/<state>/manifest-party-fixes.json. Do not edit by hand.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_as_manifest_fixes_v1')
   AS seed_apply \gset
\if :seed_apply

UPDATE elections SET manifest_url = replace(manifest_url, '"BPF"', '"BOPF"') WHERE id = 'f6a7b8c9-d0e1-2345-f012-567890122016';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_as_manifest_fixes_v1') ON CONFLICT (name) DO NOTHING;

COMMIT;

