-- Sikkim parties: every party that fielded a Sikkim VS candidate 2009-2024 (generated by scraper/src/bihar/generate-cli.ts).
-- Fill-only: existing rows (and admin edits) are never changed. Runs before the Sikkim corrections and VS seeds.

INSERT INTO parties (id, name, abbreviation, color, eci_recognition) VALUES
  ('BJP', 'Bharatiya Janata Party', NULL, '#FF7A1A', 'National'),
  ('CAP1', 'Citizen Action Party-Sikkim', NULL, '#808080', NULL),
  ('CPIM', 'Communist Party of India  (Marxist)', NULL, '#B83A3E', 'National'),
  ('HMSKP', 'Hamro Sikkim Party', 'HMSKP', '#9CA3AF', 'Unrecognised'),
  ('INC', 'Indian National Congress', NULL, '#38C6F4', 'National'),
  ('JMBP', 'Jai Maha Bharath Party', NULL, '#808080', NULL),
  ('NCP', 'Nationalist Congress Party', NULL, '#006699', NULL),
  ('SDF', 'Sikkim Democratic Front', NULL, '#808080', NULL),
  ('SGPP', 'Sikkim Gorkha Prajatantric Party', 'SGPP', '#9CA3AF', 'Unrecognised'),
  ('SHRP_SK', 'Sikkim Himali Rajya Parishad Party', 'SHRP', '#9CA3AF', 'Unrecognised'),
  ('SJEP', 'Sikkim Jan-Ekta Party', 'SJEP', '#9CA3AF', 'Unrecognised'),
  ('SKM', 'Sikkim Krantikari Morcha', NULL, '#FF4500', NULL),
  ('SKPP', 'Sikkim Republican Party', 'SKPP', '#9CA3AF', 'Unrecognised'),
  ('SRMP', 'Sikkim Rajya Manch Party', 'SRMP', '#9CA3AF', 'Unrecognised'),
  ('SUTF', 'Sikkim United Front', 'SUTF', '#9CA3AF', 'Unrecognised'),
  ('TMC', 'All India Trinamool Congress', NULL, '#00CC44', NULL)
ON CONFLICT (id) DO NOTHING;
