BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/logos/AISF.svg', 'https://commons.wikimedia.org/wiki/File:ISF_flag.svg', 'jayantanth', 'Public domain'),
  ('/symbols/eci/AISF.jpg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Envelope.jpg', 'Election Commission of India', 'GODL-India'),
  ('/symbols/logos/AJUP.png', 'https://commons.wikimedia.org/wiki/File:AJUPFlag.png', 'Karl Emanuel Jacob', 'CC0'),
  ('/symbols/eci/AJUP.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Whistle.svg', 'Election Commission of India', 'CC0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the West Bengal 2026 top parties, researched with sources (scraper/data/wb/
-- parties-2026.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_wb_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'ISF'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2021),
  leader_name = COALESCE(leader_name, 'Nawsad Siddique'),
  headquarters = COALESCE(headquarters, 'Furfura Sharif, West Bengal'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/All_India_Secular_Front'),
  description = COALESCE(description, 'A West Bengal party, popularly the Indian Secular Front, founded in 2021 by the Furfura Sharif cleric Abbas Siddiqui and chaired by his brother Nawsad Siddique. It fought the 2026 election with the Left Front, contesting 30 seats and holding Bhangar, its only win.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#0204EF' ELSE color END
WHERE id = 'AISF';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AJUP'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2025),
  leader_name = COALESCE(leader_name, 'Humayun Kabir'),
  headquarters = COALESCE(headquarters, 'Saktipur, West Bengal'),
  website = COALESCE(website, 'https://ajup.net/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Aam_Janata_Unnayan_Party'),
  description = COALESCE(description, 'A Murshidabad-based party founded in December 2025 by Humayun Kabir after his suspension from the Trinamool Congress. It contested 143 seats in its first election in 2026 and won 2, both by Kabir himself in Naoda and Rejinagar.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#8AB800' ELSE color END
WHERE id = 'AJUP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'BGPM'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2021),
  leader_name = COALESCE(leader_name, 'Anit Thapa'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Bharatiya_Gorkha_Prajatantrik_Morcha'),
  description = COALESCE(description, 'A Darjeeling hills party founded in 2021 by Anit Thapa. An ally of the Trinamool Congress, it contested the three hill seats under its own symbol in 2026 and lost all three to the BJP.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FFEF03' ELSE color END
WHERE id = 'BGPM';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_wb_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

