BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/eci/PPA.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Maize.svg', 'Abilngeorge', 'CC BY-SA 4.0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Arunachal Pradesh 2024 top parties, researched with sources (scraper/data/ar/
-- parties-2024.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_ar_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'PPA'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1977),
  leader_name = COALESCE(leader_name, 'Nabam Vivek'),
  headquarters = COALESCE(headquarters, 'Mowb-II, Near AG Office, Itanagar, Arunachal Pradesh'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/People%27s_Party_of_Arunachal'),
  description = COALESCE(description, 'Arunachal Pradesh''s oldest regional party, founded in 1977 by Bakin Pertin; it briefly governed the territory under Tomo Riba in 1979. In September 2016 Chief Minister Pema Khandu and 42 other Congress MLAs moved to the PPA, and after the party suspended Khandu that December, he and 32 of its MLAs joined the BJP. In 2024 it won 2 of 60 seats with about 7.2% of the vote, and four NPP MLAs switched to it in 2025, taking it to six.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#008000' ELSE color END
WHERE id = 'PPA';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_ar_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

