BEGIN;

-- Run once (seed_runs). Images moved from Vercel Blob (store suspended 2026-10-04) to S3 under the same keys
-- (scraper/src/bihar/media-migrate-cli.ts re-hosted them from their sources). Rewrites stored URLs still on the
-- Blob host; a URL an admin changed since is left alone. Generated by scraper/src/media-rewrite-cli.ts.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_media_s3_v1') AS seed_apply \gset
\if :seed_apply

UPDATE persons SET photo_url = 'https://matdaanpulse-media.s3.ap-south-1.amazonaws.com' || substr(photo_url, 56) WHERE photo_url LIKE 'https://ont9tlwrlxhj4iwf.public.blob.vercel-storage.com/%';
UPDATE parties SET symbol_url = 'https://matdaanpulse-media.s3.ap-south-1.amazonaws.com' || substr(symbol_url, 56) WHERE symbol_url LIKE 'https://ont9tlwrlxhj4iwf.public.blob.vercel-storage.com/%';
UPDATE parties SET eci_symbol_url = 'https://matdaanpulse-media.s3.ap-south-1.amazonaws.com' || substr(eci_symbol_url, 56) WHERE eci_symbol_url LIKE 'https://ont9tlwrlxhj4iwf.public.blob.vercel-storage.com/%';
UPDATE image_credits c SET url = 'https://matdaanpulse-media.s3.ap-south-1.amazonaws.com' || substr(c.url, 56) WHERE c.url LIKE 'https://ont9tlwrlxhj4iwf.public.blob.vercel-storage.com/%'
  AND NOT EXISTS (SELECT 1 FROM image_credits d WHERE d.url = 'https://matdaanpulse-media.s3.ap-south-1.amazonaws.com' || substr(c.url, 56));

\endif
INSERT INTO seed_runs (name) VALUES ('seed_media_s3_v1') ON CONFLICT (name) DO NOTHING;

COMMIT;
