BEGIN;

-- Run once (seed_runs). Sikkim VS 2024 winners' affidavits from MyNeta (ADR), generated by
-- scraper/src/bihar/affidavits-cli.ts. Fill-only: values an admin entered are never overwritten.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_sk_affidavits')
   AS seed_apply \gset
\if :seed_apply

UPDATE candidates c SET criminal_cases = COALESCE(c.criminal_cases, v.criminal_cases::smallint),
  assets = COALESCE(c.assets, v.assets::bigint), liabilities = COALESCE(c.liabilities, v.liabilities::bigint)
FROM (VALUES
  ('1f24231f-1173-5189-94dc-a8277783f90d', 0, 260604149, 0, '12th Pass'),
  ('630a77a5-fbc0-5431-a048-2881f4c634a8', 0, 55635488, 895252, 'Graduate'),
  ('2d682a76-3b30-5483-931c-a6f1f7cb0fe3', 0, 17749953, 0, '12th Pass'),
  ('c50e7117-6edf-50c8-b91c-0dd47ea0ab2d', 0, 60149903, 0, 'Graduate'),
  ('a933398a-35fc-51c0-ae89-5fbe77951d0d', 0, 75448284, 5081382, 'Graduate'),
  ('7ef53eab-ee38-529a-9c0d-3d801dd784d8', 0, 1375229860, 70504729, '8th Pass'),
  ('f6d794d8-c5ff-587b-b50e-22d2e0333713', 0, 439890827, 2000000, 'Post Graduate'),
  ('8089fa7e-34e4-59eb-9ec9-d5de592e9630', 0, 77946544, 15988190, '12th Pass'),
  ('be3f63c1-2270-541d-8ac9-eab6a6b87689', 0, NULL, NULL, '10th Pass'),
  ('e58e8c3a-840d-50d0-8eb5-375687bc4731', 0, 741091903, 190150431, 'Graduate'),
  ('af0300ae-667a-533d-8553-690003f1dcd7', 0, 659735237, 0, '10th Pass'),
  ('6ab605ab-34d3-5b32-a99b-dcca753c3790', 0, 18497959, 9060648, 'Graduate'),
  ('707c2ee6-ff85-5fb7-b9fc-1f7cc3d9f362', 0, 194892056, 0, 'Post Graduate'),
  ('3e214c28-530b-542f-844d-68fb90375455', 0, 86660333, 4430431, '10th Pass'),
  ('ff3f3c4a-7ee2-571f-bf4a-ce11c6ea7718', 0, 310031828, 11176797, 'Post Graduate'),
  ('7ea7b336-8fe6-55dc-a7cf-48d294e902b6', 0, 42375680, 1500000, 'Graduate'),
  ('c5bfce73-8ee3-5ad5-b142-4c77105c97f2', 0, 329776708, 0, 'Graduate'),
  ('66a8c5f5-1e54-5875-8590-307907c5d406', 0, NULL, NULL, '12th Pass'),
  ('831c69d3-8948-5053-b43b-33e5ed132b4b', 0, 6730050, 310299, 'Graduate'),
  ('85d097ac-9d14-5b08-a576-8e3b3abd140e', 1, 66921255, 1500000, 'Graduate'),
  ('4ad0d048-d0d1-540f-b530-863e55a22ffa', 0, 297569235, 0, 'Graduate'),
  ('bf46f292-a560-51f1-9e7d-401b9f4fcd5e', 0, 12968600, 0, 'Literate'),
  ('035e000e-8848-5a60-8d14-bf9f69c68a18', 0, 71840152, 595016, '8th Pass'),
  ('8d8f0091-0168-514c-97df-2ba5dc07bd2e', 0, 582707142, 232187700, 'Others'),
  ('0a232953-3ef8-5c22-9f1f-e9bfe4aea00b', 1, 66921255, 1500000, 'Graduate'),
  ('29dd853b-4e25-597a-8cf7-58dcd56b6e75', 0, 113541146, 455814, '12th Pass'),
  ('18198716-911f-51c5-8048-0cdd4841e3dc', 0, NULL, NULL, '12th Pass'),
  ('93826bdd-c8fa-592c-af05-44543efea934', 0, 101225968, 69653610, 'Others'),
  ('db163ed7-d87c-5595-a41d-4e0307dc6cbe', 0, 85539544, 0, 'Graduate Professional'),
  ('09c4cc92-d4b7-567e-81de-94d156192e1b', 0, 61716673, 15678534, 'Graduate'),
  ('43ab0fb8-860f-5fee-b125-95d0a072830e', 0, 15853115, 0, 'Graduate'),
  ('bc5098ab-03a8-57ee-9ad2-5b1e58062ff5', 0, 78145776, 2519191, 'Graduate')
) AS v(id, criminal_cases, assets, liabilities, education)
WHERE c.id = v.id::uuid;
UPDATE persons p SET education = COALESCE(p.education, v.education)
FROM (VALUES
  ('1f24231f-1173-5189-94dc-a8277783f90d', 0, 260604149, 0, '12th Pass'),
  ('630a77a5-fbc0-5431-a048-2881f4c634a8', 0, 55635488, 895252, 'Graduate'),
  ('2d682a76-3b30-5483-931c-a6f1f7cb0fe3', 0, 17749953, 0, '12th Pass'),
  ('c50e7117-6edf-50c8-b91c-0dd47ea0ab2d', 0, 60149903, 0, 'Graduate'),
  ('a933398a-35fc-51c0-ae89-5fbe77951d0d', 0, 75448284, 5081382, 'Graduate'),
  ('7ef53eab-ee38-529a-9c0d-3d801dd784d8', 0, 1375229860, 70504729, '8th Pass'),
  ('f6d794d8-c5ff-587b-b50e-22d2e0333713', 0, 439890827, 2000000, 'Post Graduate'),
  ('8089fa7e-34e4-59eb-9ec9-d5de592e9630', 0, 77946544, 15988190, '12th Pass'),
  ('be3f63c1-2270-541d-8ac9-eab6a6b87689', 0, NULL, NULL, '10th Pass'),
  ('e58e8c3a-840d-50d0-8eb5-375687bc4731', 0, 741091903, 190150431, 'Graduate'),
  ('af0300ae-667a-533d-8553-690003f1dcd7', 0, 659735237, 0, '10th Pass'),
  ('6ab605ab-34d3-5b32-a99b-dcca753c3790', 0, 18497959, 9060648, 'Graduate'),
  ('707c2ee6-ff85-5fb7-b9fc-1f7cc3d9f362', 0, 194892056, 0, 'Post Graduate'),
  ('3e214c28-530b-542f-844d-68fb90375455', 0, 86660333, 4430431, '10th Pass'),
  ('ff3f3c4a-7ee2-571f-bf4a-ce11c6ea7718', 0, 310031828, 11176797, 'Post Graduate'),
  ('7ea7b336-8fe6-55dc-a7cf-48d294e902b6', 0, 42375680, 1500000, 'Graduate'),
  ('c5bfce73-8ee3-5ad5-b142-4c77105c97f2', 0, 329776708, 0, 'Graduate'),
  ('66a8c5f5-1e54-5875-8590-307907c5d406', 0, NULL, NULL, '12th Pass'),
  ('831c69d3-8948-5053-b43b-33e5ed132b4b', 0, 6730050, 310299, 'Graduate'),
  ('85d097ac-9d14-5b08-a576-8e3b3abd140e', 1, 66921255, 1500000, 'Graduate'),
  ('4ad0d048-d0d1-540f-b530-863e55a22ffa', 0, 297569235, 0, 'Graduate'),
  ('bf46f292-a560-51f1-9e7d-401b9f4fcd5e', 0, 12968600, 0, 'Literate'),
  ('035e000e-8848-5a60-8d14-bf9f69c68a18', 0, 71840152, 595016, '8th Pass'),
  ('8d8f0091-0168-514c-97df-2ba5dc07bd2e', 0, 582707142, 232187700, 'Others'),
  ('0a232953-3ef8-5c22-9f1f-e9bfe4aea00b', 1, 66921255, 1500000, 'Graduate'),
  ('29dd853b-4e25-597a-8cf7-58dcd56b6e75', 0, 113541146, 455814, '12th Pass'),
  ('18198716-911f-51c5-8048-0cdd4841e3dc', 0, NULL, NULL, '12th Pass'),
  ('93826bdd-c8fa-592c-af05-44543efea934', 0, 101225968, 69653610, 'Others'),
  ('db163ed7-d87c-5595-a41d-4e0307dc6cbe', 0, 85539544, 0, 'Graduate Professional'),
  ('09c4cc92-d4b7-567e-81de-94d156192e1b', 0, 61716673, 15678534, 'Graduate'),
  ('43ab0fb8-860f-5fee-b125-95d0a072830e', 0, 15853115, 0, 'Graduate'),
  ('bc5098ab-03a8-57ee-9ad2-5b1e58062ff5', 0, 78145776, 2519191, 'Graduate')
) AS v(id, criminal_cases, assets, liabilities, education)
JOIN candidates c ON c.id = v.id::uuid
WHERE p.id = c.person_id;

\endif
INSERT INTO seed_runs (name) VALUES ('seed_sk_affidavits') ON CONFLICT (name) DO NOTHING;

COMMIT;

