BEGIN;

-- Run once (seed_runs). Points the Kerala manifests at the party ids the ECI data uses (a published manifest is
-- never rewritten by the year seeds). Generated by scraper/src/bihar/generate-cli.ts from
-- scraper/data/<state>/manifest-party-fixes.json. Do not edit by hand.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_kl_manifest_fixes_v1')
   AS seed_apply \gset
\if :seed_apply

UPDATE elections SET manifest_url = replace(manifest_url, '"MUL"', '"IUML"') WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232011';
UPDATE elections SET manifest_url = replace(manifest_url, '"LJD"', '"LJD_BR"') WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232021';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_kl_manifest_fixes_v1') ON CONFLICT (name) DO NOTHING;

COMMIT;

