BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/eci/RJD.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Hurricane_Lamp.png', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/eci/JDU.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Arrow.svg', 'Abilngeorge', 'CC BY-SA 3.0'),
  ('/symbols/eci/LJPRV.jpg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Helicopter.jpg', 'Election Commission of India', 'CC BY-SA 4.0'),
  ('/symbols/eci/JSP.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_School_Bag.png', 'Santhosharu', 'CC BY-SA 4.0'),
  ('/symbols/eci/CPIML.png', 'https://commons.wikimedia.org/wiki/File:Flag_Logo_of_CPIML.png', 'Atharvgairola692004', 'CC BY-SA 4.0'),
  ('/symbols/eci/AIMIM.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Kite.svg', 'Junior Jumper (formerly Tæ)', 'CC BY-SA 4.0'),
  ('/symbols/logos/BSP.svg', 'https://commons.wikimedia.org/wiki/File:Elephant_Bahujan_Samaj_Party.svg', 'Furfur', 'CC BY-SA 3.0'),
  ('/symbols/eci/VIP.jpg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Boat_with_Man_and_Sail.jpg', 'Election Commission of India', 'CC BY-SA 4.0'),
  ('/symbols/eci/HAMS.jpg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Pan.jpg', 'Election Commission of India', 'CC BY-SA 4.0'),
  ('/symbols/eci/RLM.jpg', 'https://commons.wikimedia.org/wiki/File:Gas_Cylinder.jpg', 'Faiznkm', 'CC BY-SA 4.0'),
  ('/symbols/logos/IIP.png', 'https://commons.wikimedia.org/wiki/File:Logo_of_Indian_Inclusive_Party.png', 'Subaltern1', 'CC BY-SA 4.0'),
  ('/symbols/eci/IIP.jpg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Trowel.jpg', 'Election Commission of India', 'CC BY-SA 4.0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Bihar 2025 top parties, researched with sources (scraper/data/bihar/
-- parties-2025.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_bihar_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'RJD'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1997),
  leader_name = COALESCE(leader_name, 'Lalu Prasad Yadav'),
  headquarters = COALESCE(headquarters, 'New Delhi, Delhi'),
  website = COALESCE(website, 'https://rjd.co.in/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Rashtriya_Janata_Dal'),
  description = COALESCE(description, 'A Bihar-based state party founded in 1997 by Lalu Prasad Yadav after a split from the Janata Dal. It led the Mahagathbandhan in the 2025 election with Tejashwi Yadav as its chief-ministerial face.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#056D05' ELSE color END
WHERE id = 'RJD';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'BJP'),
  eci_recognition = COALESCE(eci_recognition, 'National'),
  founded_year = COALESCE(founded_year, 1980),
  leader_name = COALESCE(leader_name, 'J. P. Nadda'),
  headquarters = COALESCE(headquarters, 'New Delhi, Delhi'),
  website = COALESCE(website, 'https://www.bjp.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Bharatiya_Janata_Party'),
  description = COALESCE(description, 'A national party founded in 1980 as the successor to the Bharatiya Jana Sangh and the leading member of the National Democratic Alliance. It contested 101 seats in Bihar in 2025 as part of the NDA.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FF9933' ELSE color END
WHERE id = 'BJP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'JD(U)'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2003),
  leader_name = COALESCE(leader_name, 'Nitish Kumar'),
  headquarters = COALESCE(headquarters, 'New Delhi, Delhi'),
  website = COALESCE(website, 'https://jdu.org.in/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Janata_Dal_(United)'),
  description = COALESCE(description, 'A socialist party formed in 2003 by Sharad Yadav, George Fernandes and Nitish Kumar, with its main base in Bihar. It contested the 2025 election in the NDA under Chief Minister Nitish Kumar.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#003366' ELSE color END
WHERE id = 'JDU';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'INC'),
  eci_recognition = COALESCE(eci_recognition, 'National'),
  founded_year = COALESCE(founded_year, 1885),
  leader_name = COALESCE(leader_name, 'Mallikarjun Kharge'),
  headquarters = COALESCE(headquarters, 'New Delhi, Delhi'),
  website = COALESCE(website, 'https://inc.in/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Indian_National_Congress'),
  description = COALESCE(description, 'India''s oldest national party, founded in 1885. In Bihar in 2025 it was a junior partner of the RJD-led Mahagathbandhan.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#00BFFF' ELSE color END
WHERE id = 'INC';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'LJP(RV)'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2021),
  leader_name = COALESCE(leader_name, 'Chirag Paswan'),
  headquarters = COALESCE(headquarters, 'Patna, Bihar'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Lok_Janshakti_Party_(Ram_Vilas)'),
  description = COALESCE(description, 'Formed in 2021 by Chirag Paswan after the split of Ram Vilas Paswan''s Lok Janshakti Party, with a Dalit (Paswan) support base in Bihar. It contested 28 seats in 2025 as an NDA member.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#5B006A' ELSE color END
WHERE id = 'LJPRV';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'JSP'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2024),
  leader_name = COALESCE(leader_name, 'Uday Singh'),
  headquarters = COALESCE(headquarters, 'New Delhi, Delhi'),
  website = COALESCE(website, 'https://www.jansuraaj.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Jan_Suraaj_Party'),
  description = COALESCE(description, 'A party launched in 2024 by political strategist Prashant Kishor out of his Jan Suraaj campaign in Bihar. It contested the 2025 election on its own, outside both the NDA and the Mahagathbandhan.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FFCD19' ELSE color END
WHERE id = 'JSP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'CPI(ML)L'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1974),
  leader_name = COALESCE(leader_name, 'Dipankar Bhattacharya'),
  headquarters = COALESCE(headquarters, 'Delhi'),
  website = COALESCE(website, 'https://cpiml.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Communist_Party_of_India_(Marxist–Leninist)_Liberation'),
  description = COALESCE(description, 'A far-left communist party reorganised in 1974, whose strongest base is among rural poor and landless voters in Bihar. It was part of the Mahagathbandhan in 2025.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#C41301' ELSE color END
WHERE id = 'CPIML';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AIMIM'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1927),
  leader_name = COALESCE(leader_name, 'Asaduddin Owaisi'),
  headquarters = COALESCE(headquarters, 'Hyderabad, Telangana'),
  website = COALESCE(website, 'https://www.aimim.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/All_India_Majlis-e-Ittehadul_Muslimeen'),
  description = COALESCE(description, 'A Hyderabad-based party with roots in the Majlis-e-Ittehadul Muslimeen of 1927, led by Asaduddin Owaisi, whose Bihar base is in the Muslim-majority Seemanchal region. In 2025 it led its own Grand Democratic Alliance, outside the NDA and the Mahagathbandhan.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#0C6B4B' ELSE color END
WHERE id = 'AIMIM';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'BSP'),
  eci_recognition = COALESCE(eci_recognition, 'National'),
  founded_year = COALESCE(founded_year, 1984),
  leader_name = COALESCE(leader_name, 'Mayawati'),
  headquarters = COALESCE(headquarters, 'New Delhi, Delhi'),
  website = COALESCE(website, 'https://bahujansamajparty.net/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Bahujan_Samaj_Party'),
  description = COALESCE(description, 'A national party founded by Kanshi Ram in 1984 to represent Dalits and other marginalised communities, led by Mayawati. It contested the 2025 Bihar election outside both major alliances.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#22409A' ELSE color END
WHERE id = 'BSP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'VIP'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2018),
  leader_name = COALESCE(leader_name, 'Mukesh Sahani'),
  headquarters = COALESCE(headquarters, 'Patna, Bihar'),
  website = COALESCE(website, 'https://www.vipparty.in/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Vikassheel_Insaan_Party'),
  description = COALESCE(description, 'A Bihar party founded in 2018 by Mukesh Sahani, drawing on the Nishad (Mallah) and allied riverine communities. It was in the Mahagathbandhan in 2025, with Sahani named its deputy chief-ministerial face.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#1E74BF' ELSE color END
WHERE id = 'VIP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'HAM(S)'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2015),
  leader_name = COALESCE(leader_name, 'Santosh Kumar Suman'),
  headquarters = COALESCE(headquarters, 'Patna, Bihar'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Hindustani_Awam_Morcha_(Secular)'),
  description = COALESCE(description, 'A Bihar party founded in 2015 by former chief minister Jitan Ram Manjhi after he left the JD(U), with a Mahadalit base. It contested six seats in 2025 as part of the NDA.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#F5D62A' ELSE color END
WHERE id = 'HAMS';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'RLM'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2023),
  leader_name = COALESCE(leader_name, 'Upendra Kushwaha'),
  headquarters = COALESCE(headquarters, 'Patna, Bihar'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Rashtriya_Lok_Morcha'),
  description = COALESCE(description, 'A Bihar party founded in 2023 by Upendra Kushwaha after he left the JD(U), drawing mainly on Kushwaha (Koeri) voters. It contested six seats in 2025 as part of the NDA.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#100CA4' ELSE color END
WHERE id = 'RLM';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'CPI(M)'),
  eci_recognition = COALESCE(eci_recognition, 'National'),
  founded_year = COALESCE(founded_year, 1964),
  leader_name = COALESCE(leader_name, 'M. A. Baby'),
  headquarters = COALESCE(headquarters, 'New Delhi, Delhi'),
  website = COALESCE(website, 'https://cpim.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Communist_Party_of_India_(Marxist)'),
  description = COALESCE(description, 'A national communist party formed in 1964 by a split from the Communist Party of India, strongest in Kerala, with a small presence in Bihar. It contested four seats in 2025 within the Mahagathbandhan.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#CC0D0D' ELSE color END
WHERE id = 'CPIM';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'IIP'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2025),
  leader_name = COALESCE(leader_name, 'Indrajeet Prasad Gupta'),
  headquarters = COALESCE(headquarters, 'Patna, Bihar'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Indian_Inclusive_Party'),
  description = COALESCE(description, 'A Bihar party founded in October 2025 by Indrajeet Prasad Gupta, shortly before the election. It joined the Mahagathbandhan and contested three seats.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#0259FF' ELSE color END
WHERE id = 'IIP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'CPI'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1925),
  leader_name = COALESCE(leader_name, 'D. Raja'),
  headquarters = COALESCE(headquarters, 'New Delhi, Delhi'),
  website = COALESCE(website, 'https://www.communistparty.in/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Communist_Party_of_India'),
  description = COALESCE(description, 'India''s oldest communist party, founded in 1925, which lost national-party status in 2023. It contested nine seats in Bihar in 2025 as part of the Mahagathbandhan.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#F50222' ELSE color END
WHERE id = 'CPI';
UPDATE parties SET symbol_url = NULL WHERE id = 'HAMS' AND symbol_url = '/symbols/logos/HAMS.svg';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_bihar_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

