BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/logos/TDP.png', 'https://commons.wikimedia.org/wiki/File:Telugu_Desam_Party_Flag.png', '456legend', 'CC BY-SA 4.0'),
  ('/symbols/eci/TDP.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Cycle.png', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/eci/YSRCP.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Ceiling_Fan.svg', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/logos/JP.png', 'https://commons.wikimedia.org/wiki/File:Janasena_Party_Flag.png', '456legend', 'CC BY-SA 4.0'),
  ('/symbols/eci/JP.svg', 'https://commons.wikimedia.org/wiki/File:Indian_election_symbol_glass_tumbler.svg', 'Eelelectric25', 'CC BY-SA 4.0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Andhra Pradesh 2024 top parties, researched with sources (scraper/data/ap/
-- parties-2024.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_ap_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'TDP'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1982),
  leader_name = COALESCE(leader_name, 'N. Chandrababu Naidu'),
  headquarters = COALESCE(headquarters, 'N. T. R. Bhavan, Mangalagiri, Andhra Pradesh'),
  website = COALESCE(website, 'https://www.telugudesam.org'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Telugu_Desam_Party'),
  description = COALESCE(description, 'A Telugu regional party founded in March 1982 by the film actor N. T. Rama Rao, which formed its first government in undivided Andhra Pradesh in 1983; N. Chandrababu Naidu has led it since 1995. After the state''s bifurcation it governed the new Andhra Pradesh from 2014 to 2019 and then lost to the YSR Congress Party. In 2024, contesting with the Jana Sena Party and the BJP as the NDA, it won 135 of 175 seats on its own (the alliance took 164), and Naidu returned as Chief Minister.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FFED00' ELSE color END
WHERE id = 'TDP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'YSRCP'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2011),
  leader_name = COALESCE(leader_name, 'Y. S. Jagan Mohan Reddy'),
  headquarters = COALESCE(headquarters, 'Plot no. 13, Suryadevara Township, Tadepalli, Guntur district, Andhra Pradesh 522501'),
  website = COALESCE(website, 'https://www.ysrcongress.com'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/YSR_Congress_Party'),
  description = COALESCE(description, 'A regional party formed in March 2011 by Y. S. Jagan Mohan Reddy after he left the Congress following the death of his father, Chief Minister Y. S. Rajasekhara Reddy; it took over a party first registered by a supporter, K. Shiva Kumar. It was the main opposition from 2014 and won 151 of 175 seats in 2019, when Jagan became Chief Minister. In 2024 it fell to 11 seats against the TDP-led NDA, short of the number needed for Leader of the Opposition status.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#1569C7' ELSE color END
WHERE id = 'YSRCP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'JSP'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2014),
  leader_name = COALESCE(leader_name, 'Pawan Kalyan'),
  headquarters = COALESCE(headquarters, 'Mangalagiri, Guntur district, Andhra Pradesh'),
  website = COALESCE(website, 'https://www.janasenaparty.org'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Janasena_Party'),
  description = COALESCE(description, 'A regional party founded in March 2014 by the Telugu film actor Pawan Kalyan; it backed the TDP and BJP in 2014 without contesting, and won a single seat in 2019, when it fought alongside the BSP, CPI and CPI(M). In 2024 it contested 21 seats in the NDA alliance with the TDP and BJP and won all 21 of 175, and Pawan Kalyan became Deputy Chief Minister. The Election Commission recognised it as a state party in January 2025 and reserved its glass tumbler symbol.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#E8232A' ELSE color END
WHERE id = 'JP';
UPDATE parties SET symbol_url = NULL WHERE id = 'YSRCP' AND symbol_url = '/symbols/logos/YSRCP.svg';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_ap_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

