BEGIN;

-- Party state units and their leaders (migration 023). Run once: admins will edit units later. Generated by
-- scraper/src/party-model-cli.ts from the sourced scraper/data/parties/units-*.json (user-approved).
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_party_units_v2')
   AS seed_apply \gset
\if :seed_apply

INSERT INTO party_units (party_id, state_id, eci_recognition, office, website) VALUES ('BJP', 30, 'National', 'State Office, Golitar, Singtam, District Pakyong 737134', NULL) ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('BJP', 30, 'state_president', (SELECT person_id FROM candidates WHERE id = '7fde3978-ebef-5987-8aa4-f97c11d2a348'), 'Dilli Ram Thapa', '2023-02-04', NULL, 'https://eastmojo.com/sikkim/2023/02/04/bjp-appoints-d-r-thapa-as-new-sikkim-unit-chief/') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('BJP', 30, 'state_president', NULL, 'D. B. Chauhan', NULL, '2022-12-13', 'https://eastmojo.com/sikkim/2022/12/13/disillusioned-with-central-leadership-sikkim-bjp-president-resigns/') ON CONFLICT DO NOTHING;
INSERT INTO party_units (party_id, state_id, eci_recognition, office, website) VALUES ('CAP1', 30, 'State', 'Adampool, near Gangtok', NULL) ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('CAP1', 30, 'state_president', (SELECT person_id FROM candidates WHERE id = '06791d34-b8b4-5181-a992-21534551ebe0'), 'Ganesh Kumar Rai', NULL, NULL, 'https://eastmojo.com/news/2025/07/29/citizen-action-party-accuses-sikkim-govt-of-political-violence/') ON CONFLICT DO NOTHING;
INSERT INTO party_units (party_id, state_id, eci_recognition, office, website) VALUES ('INC', 30, 'National', 'NH-31A, 5th Mile, Tadong, Gangtok 737102', NULL) ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('INC', 30, 'state_president', (SELECT person_id FROM candidates WHERE id = 'd714f8aa-9290-5cb2-8645-44830963c0e5'), 'Gopal Chettri', '2023-09-23', NULL, 'https://www.deccanherald.com/india/sikkim/gopal-chettri-appointed-president-of-congress-sikkim-unit-2698500') ON CONFLICT DO NOTHING;
INSERT INTO party_units (party_id, state_id, eci_recognition, office, website) VALUES ('SDF', 30, 'State', 'S.D.F. Bhawan, Indira Bypass, Gangtok', NULL) ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('SDF', 30, 'state_president', (SELECT person_id FROM candidates WHERE id = '3a9c0815-3eea-5bb6-aad8-ed66c75fbb36'), 'Pawan Kumar Chamling', '1993-03-04', NULL, 'https://en.wikipedia.org/wiki/Pawan_Kumar_Chamling') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('SDF', 30, 'legislature_leader', (SELECT person_id FROM candidates WHERE id = '8d8f0091-0168-514c-97df-2ba5dc07bd2e'), 'Tenzing Norbu Lamtha', NULL, '2024-07-10', 'https://eastmojo.com/sikkim/2024/07/10/sikkim-assembly-goes-opposition-less-as-lone-sdf-legislator-joins-skm/') ON CONFLICT DO NOTHING;
INSERT INTO party_units (party_id, state_id, eci_recognition, office, website) VALUES ('SKM', 30, 'State', 'Ghaley Compound, Tibet Road, Gangtok 737101', 'https://www.sikkimkrantikarimorcha.org/') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('SKM', 30, 'state_president', (SELECT person_id FROM candidates WHERE id = '17a3e4ad-bee9-5b83-9e5e-da26b718b466'), 'Prem Singh Tamang', '2013-02-04', NULL, 'https://www.sikkimkrantikarimorcha.org/') ON CONFLICT DO NOTHING;
INSERT INTO party_unit_roles (party_id, state_id, role, person_id, person_name, from_date, to_date, source_url) VALUES ('SKM', 30, 'legislature_leader', (SELECT person_id FROM candidates WHERE id = '17a3e4ad-bee9-5b83-9e5e-da26b718b466'), 'Prem Singh Tamang', '2019-05-27', NULL, 'https://en.wikipedia.org/wiki/Prem_Singh_Tamang') ON CONFLICT DO NOTHING;

\endif
INSERT INTO seed_runs (name) VALUES ('seed_party_units_v2') ON CONFLICT (name) DO NOTHING;

COMMIT;
