BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/eci/RSP.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Spade_and_Stoker.png', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/logos/NCPSP.png', 'https://commons.wikimedia.org/wiki/File:NCP–SP_Flag.png', 'Soumava2002', 'CC BY-SA 4.0'),
  ('/symbols/eci/NCPSP.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Man_Blowing_Turha.png', 'Election Commission of India', 'Public domain'),
  ('/symbols/logos/RMPI.jpg', 'https://commons.wikimedia.org/wiki/File:RMPI_flag.jpg', 'RMPI', 'Public domain'),
  ('/symbols/logos/ISJD.png', 'https://commons.wikimedia.org/wiki/File:Indian_Socialist_Janata_Dal_Flag.png', 'XYZ 250706', 'CC0'),
  ('/symbols/logos/KRSPLM.png', 'https://commons.wikimedia.org/wiki/File:RSP_(Leninist)_Flag.png', 'Soumava2002', 'CC BY-SA 4.0'),
  ('/symbols/logos/IUML.svg', 'https://commons.wikimedia.org/wiki/File:Flag_of_the_Indian_Union_Muslim_League.svg', 'Zscout370', 'Public domain'),
  ('/symbols/eci/IUML.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Lader.svg', 'Junior Jumper (formerly Tæ)', 'CC BY-SA 4.0'),
  ('/symbols/logos/KECM.svg', 'https://commons.wikimedia.org/wiki/File:Kerala-Congress-flag.svg', 'Nichalp (assumed)', 'Public domain'),
  ('/symbols/eci/KECM.svg', 'https://commons.wikimedia.org/wiki/File:Indian_election_symbol_two_leaves.svg', 'Furfur', 'CC BY-SA 4.0'),
  ('/symbols/eci/KEC.svg', 'https://commons.wikimedia.org/wiki/File:Auto_Rickshaw_Election_Symbol.svg', 'Election Commission of India', 'CC BY-SA 3.0'),
  ('/symbols/eci/BDJS.jpg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Coconut_Farm.jpg', 'Election Commission of India', 'CC BY-SA 4.0'),
  ('/symbols/logos/KECJ.svg', 'https://commons.wikimedia.org/wiki/File:Kerala-Congress-flag.svg', 'Nichalp (assumed)', 'Public domain'),
  ('/symbols/logos/KECB.png', 'https://commons.wikimedia.org/wiki/File:KCB.Pathanapuram.png', 'MNKary', 'CC0'),
  ('/symbols/logos/INCS.jpg', 'https://commons.wikimedia.org/wiki/File:Congress_(Secular)_Flag.jpg', 'Arjun Muraleedharan Madathiparambil', 'CC BY-SA 4.0'),
  ('/symbols/logos/CMPKSC.svg', 'https://commons.wikimedia.org/wiki/File:CMP-banner.svg', 'Nichalp', 'Public domain'),
  ('/symbols/logos/INL.png', 'https://commons.wikimedia.org/wiki/File:INL_FLAG.png', 'Shabeeb1', 'CC0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Kerala 2026 top parties, researched with sources (scraper/data/kl/
-- parties-2026.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_kl_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'RSP'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1940),
  leader_name = COALESCE(leader_name, 'Manoj Bhattacharya'),
  headquarters = COALESCE(headquarters, 'New Delhi, Delhi'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Revolutionary_Socialist_Party_(India)'),
  description = COALESCE(description, 'A Marxist party founded in 1940 with roots in the Bengal anti-colonial movement, a Left Front member in West Bengal and part of the Congress-led UDF in Kerala. In 2026 it won 3 of its 4 seats in Kerala with the UDF, while its 18 Left Front candidates in West Bengal all lost.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#D84C4C' ELSE color END
WHERE id = 'RSP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'NCP–SP'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2024),
  leader_name = COALESCE(leader_name, 'Sharad Pawar'),
  headquarters = COALESCE(headquarters, 'New Delhi, Delhi'),
  website = COALESCE(website, 'https://ncpsp.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Nationalist_Congress_Party_%E2%80%93_Sharadchandra_Pawar'),
  description = COALESCE(description, 'The party of Sharad Pawar''s faction, formed in 2024 after the Election Commission awarded the original NCP name and symbol to Ajit Pawar''s group. In Kerala it contested three seats in the LDF in 2026 and won none.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#0029B0' ELSE color END
WHERE id = 'NCPSP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'RMPI'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2016),
  leader_name = COALESCE(leader_name, 'Mangat Ram Pasla'),
  headquarters = COALESCE(headquarters, 'Jalandhar, Punjab'),
  website = COALESCE(website, 'http://www.rmpi.in/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Revolutionary_Marxist_Party_of_India'),
  description = COALESCE(description, 'A Marxist party formed in 2016 by merging Kerala''s Revolutionary Marxist Party, founded by the slain T. P. Chandrasekharan, with breakaway CPI(M) groups from other states. Backed by the UDF, its Kerala leader K. K. Rema held Vadakara in 2026.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FF0000' ELSE color END
WHERE id = 'RMPI';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'ISJD'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2026),
  leader_name = COALESCE(leader_name, 'Mathew T. Thomas'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Indian_Socialist_Janata_Dal'),
  description = COALESCE(description, 'A Kerala socialist party founded in January 2026 by Mathew T. Thomas as a breakaway from the Janata Dal (Secular). It contested two seats as part of the LDF in 2026 and won none.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#33CC00' ELSE color END
WHERE id = 'ISJD';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'RSP(L)'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2016),
  leader_name = COALESCE(leader_name, 'Kovoor Kunjumon'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Revolutionary_Socialist_Party_(Leninist)'),
  description = COALESCE(description, 'The party of Kovoor Kunjumon, known as the RSP (Leninist), formed in 2016 after a split from the Revolutionary Socialist Party and allied with the LDF. Kunjumon, who had held Kunnathur since 2001, lost the seat to the RSP in 2026.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FF0000' ELSE color END
WHERE id = 'KRSPLM';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'IUML'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1948),
  leader_name = COALESCE(leader_name, 'K. M. Kader Mohideen'),
  headquarters = COALESCE(headquarters, 'Chennai, Tamil Nadu'),
  website = COALESCE(website, 'https://iumlkerala.org'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Indian_Union_Muslim_League'),
  description = COALESCE(description, 'A Muslim community party that traces its first council to Madras in March 1948, strongest in Kerala where it is the main partner of the Congress-led UDF. In 2026 it won 22 of its 26 Kerala seats and two seats in Tamil Nadu as a DMK ally, later backing the TVK government there.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#006600' ELSE color END
WHERE id = 'IUML';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'KC(M)'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1979),
  leader_name = COALESCE(leader_name, 'Jose K. Mani'),
  headquarters = COALESCE(headquarters, 'Kottayam, Kerala'),
  website = COALESCE(website, 'https://www.keralacongressm.co.in'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Kerala_Congress_(M)'),
  description = COALESCE(description, 'A Kerala regional party founded by K. M. Mani in 1979, rooted in the Christian farming belt of central Travancore and a member of the CPI(M)-led LDF since 2020. It contested 12 seats for the LDF in 2026 and won none.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#89BADF' ELSE color END
WHERE id = 'KECM';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'KEC'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1964),
  leader_name = COALESCE(leader_name, 'P. J. Joseph'),
  headquarters = COALESCE(headquarters, 'Kottayam, Kerala'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Kerala_Congress'),
  description = COALESCE(description, 'The P. J. Joseph-led party that holds the original Kerala Congress name (the movement dates from 1964) and sits in the Congress-led UDF. It won seven of the eight seats it contested in Kerala in 2026.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#809FFF' ELSE color END
WHERE id = 'KEC';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'TTP'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2015),
  leader_name = COALESCE(leader_name, 'Sabu M. Jacob'),
  headquarters = COALESCE(headquarters, 'Kizhakkambalam, Ernakulam, Kerala'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Twenty_20_Party'),
  description = COALESCE(description, 'A party that grew out of the Kitex group''s welfare movement in Kizhakkambalam panchayat, launched by industrialist Sabu M. Jacob in 2015. It joined the NDA for 2026 and contested 19 Kerala seats without winning any.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#62C0FE' ELSE color END
WHERE id = 'TP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'BDJS'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2015),
  leader_name = COALESCE(leader_name, 'Thushar Vellappally'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Bharath_Dharma_Jana_Sena'),
  description = COALESCE(description, 'A Kerala party formed in December 2015 with backing from the Ezhava community organisation SNDP Yogam and a member of the BJP-led NDA. It contested 22 seats in Kerala in 2026 and won none.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#800000' ELSE color END
WHERE id = 'BDJS';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'KC(J)'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 1993),
  leader_name = COALESCE(leader_name, 'Anoop Jacob'),
  headquarters = COALESCE(headquarters, 'Kottayam, Kerala'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Kerala_Congress_(Jacob)'),
  description = COALESCE(description, 'A Kerala Congress faction founded by T. M. Jacob in 1993 and now led by his son Anoop Jacob, allied with the Congress-led UDF. It contested and won one seat in 2026.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#BFCFFF' ELSE color END
WHERE id = 'KECJ';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'KC(B)'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 1977),
  leader_name = COALESCE(leader_name, 'K. B. Ganesh Kumar'),
  headquarters = COALESCE(headquarters, 'Thiruvananthapuram, Kerala'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Kerala_Congress_(B)'),
  description = COALESCE(description, 'A Kerala Congress faction founded by R. Balakrishna Pillai in 1977, now chaired by his son K. B. Ganesh Kumar and part of the LDF. Its single 2026 candidate, Ganesh Kumar, lost Pathanapuram.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#2F027E' ELSE color END
WHERE id = 'KECB';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'Cong(S)'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 1978),
  leader_name = COALESCE(leader_name, 'Kadannappalli Ramachandran'),
  headquarters = COALESCE(headquarters, 'Kochi, Kerala'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Congress_(Secular)'),
  description = COALESCE(description, 'A small party that survives from the 1978 split of the Congress, led in Kerala by Kadannappalli Ramachandran and allied with the LDF. It contested one seat in 2026 and did not win.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#4FE8DB' ELSE color END
WHERE id = 'INCS';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'CMP'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  leader_name = COALESCE(leader_name, 'C. P. John'),
  headquarters = COALESCE(headquarters, 'Thiruvananthapuram, Kerala'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Communist_Marxist_Party'),
  description = COALESCE(description, 'The C. P. John-led faction of the Communist Marxist Party, which M. V. Raghavan founded in 1986 after his expulsion from the CPI(M); it is a UDF ally. John contested its only 2026 seat and won.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FF0000' ELSE color END
WHERE id = 'CMPKSC';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'INL'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 1994),
  leader_name = COALESCE(leader_name, 'Mohammad Soleiman'),
  website = COALESCE(website, 'https://indiannationalleague.party/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Indian_National_League'),
  description = COALESCE(description, 'A party formed in 1994 by Ebrahim Sulaiman Sait after he left the IUML, allied with the LDF in Kerala. It contested one seat each in Kerala and Tamil Nadu in 2026 and won neither.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#2E8B57' ELSE color END
WHERE id = 'INL';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_kl_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

