BEGIN;

-- Run once (seed_runs). Details of the Delhi 2025 top parties, researched with sources (scraper/data/dl/
-- parties-2025.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_dl_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AAP'),
  eci_recognition = COALESCE(eci_recognition, 'National'),
  founded_year = COALESCE(founded_year, 2012),
  leader_name = COALESCE(leader_name, 'Arvind Kejriwal'),
  headquarters = COALESCE(headquarters, '206, Rouse Avenue, Deen Dayal Upadhyaya Marg, New Delhi 110002'),
  website = COALESCE(website, 'https://aamaadmiparty.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Aam_Aadmi_Party'),
  description = COALESCE(description, 'A party that grew out of the 2011 anti-corruption movement, founded in 2012 by Arvind Kejriwal and recognised as a national party in 2023. After governing Delhi since 2015 it lost the 2025 election to the BJP, winning 22 of 70 seats with about 43.6% of the vote; Kejriwal lost New Delhi.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#0072B0' ELSE color END
WHERE id = 'AAP';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_dl_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

