BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/logos/AINRC.png', 'https://commons.wikimedia.org/wiki/File:All_India_N.R._Congress.png', 'Unknown (uploader states own work)', 'Public domain'),
  ('/symbols/eci/AINRC.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Jug.svg', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/eci/LJK.jpg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Watermelon.jpg', 'Election Commission of India', 'CC BY-SA 4.0'),
  ('/symbols/logos/TVK.png', 'https://commons.wikimedia.org/wiki/File:Tamilaga_Vettri_Kazhagam_(TVK)_Flag.png', 'TVK IT Wing', 'CC0'),
  ('/symbols/eci/TVK.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Whistle.svg', 'Election Commission of India', 'CC0'),
  ('/symbols/logos/DMK.svg', 'https://commons.wikimedia.org/wiki/File:Flag_DMK.svg', 'Amit6', 'Public domain'),
  ('/symbols/eci/DMK.svg', 'https://commons.wikimedia.org/wiki/File:Indian_election_symbol_rising_sun.svg', 'Furfur', 'CC BY-SA 4.0'),
  ('/symbols/logos/AIADMK.svg', 'https://commons.wikimedia.org/wiki/File:AIADMK_Flag.svg', 'KindCowboy69', 'CC BY-SA 4.0'),
  ('/symbols/eci/NTK.jpg', 'https://commons.wikimedia.org/wiki/File:NTK-EC-Symbol.jpg', 'Mohantry-3009', 'CC0'),
  ('/symbols/eci/VCK.png', 'https://commons.wikimedia.org/wiki/File:Pot_Symbol.png', 'Aharon Noraha', 'CC BY-SA 4.0'),
  ('/symbols/eci/PMK.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Mango_SVG.svg', 'Election Commission of India (election logo released by the Indian government)', 'CC BY-SA 4.0'),
  ('/symbols/eci/AIPTMMK.jpg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Coconut_Farm.jpg', 'Election Commission of India', 'CC BY-SA 4.0'),
  ('/symbols/logos/AJPK.svg', 'https://commons.wikimedia.org/wiki/File:PMK.svg', 'Arafath.riyath (PMK.jpg); derivative work: Germo', 'CC BY-SA 3.0'),
  ('/symbols/eci/AJPK.jpg', 'https://commons.wikimedia.org/wiki/File:Gas_Cylinder.jpg', 'Faiznkm', 'CC BY-SA 4.0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Puducherry 2026 top parties, researched with sources (scraper/data/py/
-- parties-2026.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_py_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AINRC'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2011),
  leader_name = COALESCE(leader_name, 'N. Rangaswamy'),
  headquarters = COALESCE(headquarters, 'Puducherry, Puducherry'),
  website = COALESCE(website, 'http://allindianrcongress.com/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/All_India_N._R._Congress'),
  description = COALESCE(description, 'A Puducherry party founded in 2011 by former Congress chief minister N. Rangaswamy, who was chief minister from 2011 to 2016 and again from 2021. It headed the NDA in 2026 and won 12 of the 16 seats it contested, the most of any party.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#89C27A' ELSE color END
WHERE id = 'AINRC';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'LJK'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2025),
  leader_name = COALESCE(leader_name, 'Jose Charles Martin'),
  headquarters = COALESCE(headquarters, 'Puducherry, Puducherry'),
  website = COALESCE(website, 'https://ljkofficial.com/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Latchiya_Jananayaka_Katchi'),
  description = COALESCE(description, 'A Puducherry party founded in December 2025 by the businessman Jose Charles Martin. It contested two seats in the NDA in 2026 and won one, with Martin elected from Kamaraj Nagar.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#002395' ELSE color END
WHERE id = 'LJK';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'NMK'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2025),
  leader_name = COALESCE(leader_name, 'G. Nehru Kuppusamy'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/G._Nehru_Kuppusamy'),
  description = COALESCE(description, 'A small Puducherry party founded by G. Nehru Kuppusamy, a former AINRC MLA who won Orleampeth as an independent in 2021. It contested two seats in the TVK-led alliance in 2026 and won one, with Kuppusamy re-elected from Orleampeth.')
WHERE id = 'NYMK';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'TVK'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2024),
  leader_name = COALESCE(leader_name, 'C. Joseph Vijay'),
  headquarters = COALESCE(headquarters, 'Panaiyur, Chennai, Tamil Nadu'),
  website = COALESCE(website, 'https://tvkvijay.com'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Tamilaga_Vettri_Kazhagam'),
  description = COALESCE(description, 'A party launched by film actor Vijay in February 2024 as a challenger to the DMK–AIADMK duopoly. In its first election in 2026 it became the largest party in Tamil Nadu with 108 of 234 seats and Vijay formed the government with outside support.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#F2B705' ELSE color END
WHERE id = 'TVK';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'DMK'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1949),
  leader_name = COALESCE(leader_name, 'M. K. Stalin'),
  headquarters = COALESCE(headquarters, 'Chennai, Tamil Nadu'),
  website = COALESCE(website, 'https://www.dmk.in/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Dravida_Munnetra_Kazhagam'),
  description = COALESCE(description, 'A Dravidian party founded by C. N. Annadurai in 1949 that led Tamil Nadu from 2021 at the head of the Secular Progressive Alliance. It lost power in 2026, winning 59 seats, and became the main opposition.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FA2223' ELSE color END
WHERE id = 'DMK';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AIADMK'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1972),
  leader_name = COALESCE(leader_name, 'Edappadi K. Palaniswami'),
  headquarters = COALESCE(headquarters, 'Chennai, Tamil Nadu'),
  website = COALESCE(website, 'https://aiadmk.com/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/All_India_Anna_Dravida_Munnetra_Kazhagam'),
  description = COALESCE(description, 'A Dravidian party founded by M. G. Ramachandran in 1972 after his split from the DMK. It led an alliance with the BJP in 2026 and won 47 seats.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#009933' ELSE color END
WHERE id = 'AIADMK';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'NTK'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1958),
  leader_name = COALESCE(leader_name, 'Seeman'),
  headquarters = COALESCE(headquarters, 'Porur, Chennai, Tamil Nadu'),
  website = COALESCE(website, 'http://www.naamtamilar.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Naam_Tamilar_Katchi'),
  description = COALESCE(description, 'A Tamil nationalist party, revived by Seeman in 2010 from S. P. Adithanar''s 1958 outfit, that always contests alone. It fielded candidates in all 234 Tamil Nadu seats in 2026, polling about 4% without winning a seat.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#B31818' ELSE color END
WHERE id = 'NTK';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'VCK'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1982),
  leader_name = COALESCE(leader_name, 'Thol. Thirumavalavan'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Viduthalai_Chiruthaigal_Katchi'),
  description = COALESCE(description, 'An Ambedkarite Dalit party led by Thol. Thirumavalavan and a long-time member of the DMK-led alliance. It won two of its eight seats in 2026 and then gave unconditional support to the TVK government.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#1E90FF' ELSE color END
WHERE id = 'VCK';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'PMK'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 1989),
  leader_name = COALESCE(leader_name, 'Anbumani Ramadoss'),
  headquarters = COALESCE(headquarters, 'Tindivanam, Tamil Nadu'),
  website = COALESCE(website, 'http://pmkofficial.com/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Pattali_Makkal_Katchi'),
  description = COALESCE(description, 'A party founded by S. Ramadoss in 1989 to represent the Vanniyar community of northern Tamil Nadu, led by his son Anbumani after a 2025 split. It contested 18 seats in the AIADMK-led alliance in 2026 and won four.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FFFF00' ELSE color END
WHERE id = 'PMK';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AIPTMMK'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2026),
  leader_name = COALESCE(leader_name, 'V. K. Sasikala'),
  description = COALESCE(description, 'A party named in March 2026 by former AIADMK interim general secretary V. K. Sasikala after she gave up her claim on the AIADMK. It led a front with the Ramadoss faction of the PMK in 2026 and won no seats.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#336633' ELSE color END
WHERE id = 'AIPTMMK';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AJPK'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2025),
  leader_name = COALESCE(leader_name, 'S. Ramadoss'),
  headquarters = COALESCE(headquarters, 'Tindivanam, Tamil Nadu'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Anaithindhiya_Jananayaka_Padhugappu_Kazhagam'),
  description = COALESCE(description, 'The party vehicle of PMK founder S. Ramadoss''s faction after his 2025 split with his son Anbumani, allied with Sasikala''s AIPTMMK in 2026 without winning a seat. It merged back into the PMK when the two resolved their dispute on 24 June 2026.')
WHERE id = 'AJPK';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_py_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

