BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/logos/AP1.jpg', 'https://commons.wikimedia.org/wiki/File:ANSU_Party_flag.jpg', 'Unrecognized', 'CC BY-SA 4.0'),
  ('/symbols/eci/AP1.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Banana.svg', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/eci/JLKM.png', 'https://commons.wikimedia.org/wiki/File:Scissors_-_Indian_Election_Symbol.png', 'Atharvgairola692004', 'CC0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Jharkhand 2024 top parties, researched with sources (scraper/data/jh/
-- parties-2024.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_jh_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AJSU'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1986),
  leader_name = COALESCE(leader_name, 'Sudesh Mahto'),
  headquarters = COALESCE(headquarters, 'Harmu Road, Ranchi 834001, Jharkhand'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/All_Jharkhand_Students_Union'),
  description = COALESCE(description, 'The All Jharkhand Students Union, founded in 1986 during the Jharkhand statehood movement and an NDA ally since 2014. In 2024 it contested 10 seats with the BJP and won only Mandu, with about 3.5% of the vote; party chief Sudesh Mahto lost Silli.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#6827B5' ELSE color END
WHERE id = 'AP1';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'JLKM'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2024),
  leader_name = COALESCE(leader_name, 'Jairam Kumar Mahato'),
  headquarters = COALESCE(headquarters, 'Indrapuri Colony, Badhraibera, Sector 12, Bokaro, Jharkhand'),
  website = COALESCE(website, 'https://jlkmparty.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Jharkhand_Loktantrik_Krantikari_Morcha'),
  description = COALESCE(description, 'A Jharkhand regional party led by language and domicile activist Jairam Kumar Mahato, grown out of the Jharkhandi Bhasha Khatiyan Sangharsh Samiti and registered in 2024. In its first assembly election it contested 68 seats and won one, Dumri (Mahato himself), with about 6.1% of the vote.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#7CB342' ELSE color END
WHERE id = 'JLKM';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_jh_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

