-- Puducherry parties: every party that fielded a Puducherry VS candidate 2011-2021 (generated by scraper/src/bihar/generate-cli.ts).
-- Fill-only: existing rows (and admin edits) are never changed. Runs before the Puducherry corrections and VS seeds.

INSERT INTO parties (id, name, abbreviation, color, eci_recognition) VALUES
  ('AGIMK', 'Agila India Makkal Kazhagam', 'AgIMK', '#9CA3AF', 'Unrecognised'),
  ('AIADMK', 'All India Anna Dravida Munnetra Kazhagam', NULL, '#006400', NULL),
  ('AINRC', 'All India N.R. Congress', 'AINRC', '#FF9933', NULL),
  ('AMMK', 'Amma Makkal Munnettra Kazagam', NULL, '#808080', NULL),
  ('BJP', 'Bharatiya Janata Party', NULL, '#FF7A1A', 'National'),
  ('BSP', 'Bahujan Samaj Party', NULL, '#4B5BD6', 'National'),
  ('CPI', 'Communist Party of India', NULL, '#FF0000', NULL),
  ('CPIM', 'Communist Party of India  (Marxist)', NULL, '#B83A3E', 'National'),
  ('CPIML', 'Communist Party of India (Marxist-Leninist) (Liberation)', 'CPI(ML)(L)', '#E5484D', 'State'),
  ('DMDK', 'Desiya Murpokku Dravida Kazhagam', NULL, '#DAA520', NULL),
  ('DMK', 'Dravida Munnetra Kazhagam', NULL, '#E30B0B', NULL),
  ('IJK', 'Indiya Jananayaka Katchi', 'IJK', '#9CA3AF', 'Unrecognised'),
  ('INC', 'Indian National Congress', NULL, '#38C6F4', 'National'),
  ('JDU', 'Janata Dal  (United)', 'JD(U)', '#1FA37A', 'State'),
  ('LJP', 'Lok Janshakti Party', NULL, '#0000CD', NULL),
  ('MDMK', 'Marumalarchi Dravida Munnetra Kazhagam', NULL, '#B22222', NULL),
  ('MIDP', 'My India Party', 'MIDP', '#9CA3AF', 'Unrecognised'),
  ('MNM', 'Makkal Needhi Maiam', 'MNM', '#FF4081', NULL),
  ('NTK', 'Naam Tamilar Katchi', NULL, '#800020', NULL),
  ('PB', 'Puratchi Bharatham', 'PB', '#9CA3AF', 'Unrecognised'),
  ('PMK', 'Pattali Makkal Katchi', NULL, '#FFD700', NULL),
  ('PUDEP', 'Puducherry Development Party', 'PUDEP', '#9CA3AF', 'Unrecognised'),
  ('RSP', 'Revolutionary Socialist Party', NULL, '#DC143C', NULL),
  ('SDPOI', 'Social Democratic Party Of India', NULL, '#808080', NULL),
  ('TAVK', 'Tamizhaga Vaazhvurimai Katchi', 'tavk', '#9CA3AF', 'Unrecognised'),
  ('VCK', 'Viduthalai Chiruthaigal Katchi', NULL, '#8B0000', NULL)
ON CONFLICT (id) DO NOTHING;
