BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/eci/BJD.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Conch.svg', 'Furfur (after Abilngeorge)', 'CC BY-SA 4.0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Odisha 2024 top parties, researched with sources (scraper/data/od/
-- parties-2024.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_od_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'BJD'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1997),
  leader_name = COALESCE(leader_name, 'Naveen Patnaik'),
  headquarters = COALESCE(headquarters, 'Sankha Bhawan, Bhubaneswar 751001, Odisha'),
  website = COALESCE(website, 'https://bjdodisha.org.in/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Biju_Janata_Dal'),
  description = COALESCE(description, 'An Odisha regional party founded in 1997 by Naveen Patnaik, named after his father Biju Patnaik, which governed the state from 2000 to 2024. In 2024 it lost power to the BJP, winning 51 of 147 seats with about 40.2% of the vote; Patnaik won Hinjili but lost Kantabanji.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#70A548' ELSE color END
WHERE id = 'BJD';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_od_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

