BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/eci/JKNC.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Plough.png', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/eci/JKPDP.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Ink_Pot_and_Pen.png', 'Abilngeorge', 'CC BY-SA 4.0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Jammu and Kashmir 2024 top parties, researched with sources (scraper/data/jk/
-- parties-2024.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_jk_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'JKNC'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1932),
  leader_name = COALESCE(leader_name, 'Farooq Abdullah'),
  headquarters = COALESCE(headquarters, 'Nawa-e-Subha, Srinagar, Jammu and Kashmir'),
  website = COALESCE(website, 'https://jknc.co.in'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Jammu_%26_Kashmir_National_Conference'),
  description = COALESCE(description, 'Founded by Sheikh Abdullah and Chaudhry Ghulam Abbas on 15 October 1932 as the All Jammu and Kashmir Muslim Conference, it took the name National Conference in 1939 and backed the princely state''s accession to India in 1947. It governed Jammu and Kashmir for most of the years until 2002 and again from 2009 to 2015, led successively by Sheikh Abdullah, his son Farooq Abdullah and grandson Omar Abdullah. In 2024, in the first assembly election since the state became a union territory in 2019, it contested in alliance with the Congress and won 42 of 90 seats, the most of any party, and Omar Abdullah was sworn in on 16 October 2024 as the union territory''s first Chief Minister.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#C41E3A' ELSE color END
WHERE id = 'JKNC';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'JKPDP'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1999),
  leader_name = COALESCE(leader_name, 'Mehbooba Mufti'),
  headquarters = COALESCE(headquarters, '2, Circuit House, Emporium Lane, Residency Road, Srinagar, Jammu and Kashmir'),
  website = COALESCE(website, 'https://jkpdp.org'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Jammu_and_Kashmir_Peoples_Democratic_Party'),
  description = COALESCE(description, 'A Kashmir-based regional party founded in 1999 by former Union Home Minister Mufti Mohammad Sayeed, who became Chief Minister in 2002 at the head of a coalition with the Congress. It emerged as the largest party in 2014 with 28 seats and formed a government with the BJP, led by Sayeed and, after his death in 2016, by his daughter Mehbooba Mufti, until the BJP withdrew in June 2018. In 2024 it contested 81 of the 90 seats and won 3, with about 8.9% of the vote, its worst result since its formation; Waheed Para became the leader of its legislators. In November 2025 it won the Budgam by-election, the seat Omar Abdullah had vacated.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#058532' ELSE color END
WHERE id = 'JKPDP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'JKPC'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 1978),
  leader_name = COALESCE(leader_name, 'Sajad Gani Lone'),
  headquarters = COALESCE(headquarters, 'J-65, Jawahar Nagar, Srinagar, Jammu and Kashmir 190008'),
  website = COALESCE(website, 'https://jkpcofficial.org'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Jammu_and_Kashmir_People%27s_Conference'),
  description = COALESCE(description, 'Founded in 1978 by Abdul Ghani Lone, a former Congress legislator who later became a separatist leader and a founder of the All Parties Hurriyat Conference; he was assassinated in Srinagar in 2002. His son Sajad Gani Lone returned the party to electoral politics, and it won two seats in 2014 and joined the PDP-BJP government, in which Lone was a minister. In 2024 it contested 15 seats and won one, Handwara, where Lone was elected by 662 votes.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#005085' ELSE color END
WHERE id = 'JKPC';
UPDATE parties SET symbol_url = NULL WHERE id = 'JKPC' AND symbol_url = '/symbols/logos/JKPC.svg';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_jk_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

