BEGIN;

-- Run once (seed_runs). Puducherry VS 2026 winners' affidavits from MyNeta (ADR), generated by
-- scraper/src/bihar/affidavits-cli.ts. Fill-only: values an admin entered are never overwritten.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_py_affidavits')
   AS seed_apply \gset
\if :seed_apply

UPDATE candidates c SET criminal_cases = COALESCE(c.criminal_cases, v.criminal_cases::smallint),
  assets = COALESCE(c.assets, v.assets::bigint), liabilities = COALESCE(c.liabilities, v.liabilities::bigint)
FROM (VALUES
  ('5ee6bf5f-b8b5-5792-b89c-f8951a977e09', 1, 96302813, 54117500, 'Graduate'),
  ('6531c581-e412-5bae-9ee9-5e1348482f47', 0, 277608000, 51332067, 'Post Graduate'),
  ('7567ec88-9d74-50bf-b5b0-f229ce599261', 0, 134341307, 20070580, 'Post Graduate'),
  ('2f2ca7e0-1bef-5f08-b7ee-2f8c186e4cc6', 0, 505816200, 34829246, '10th Pass'),
  ('e46235a5-bacf-51cc-ba1e-ab937fd9aaba', 0, 64247543, 10131539, '12th Pass'),
  ('cb881302-b776-5b92-aacc-44b3e49d6317', 11, 297620500, 2000000, '8th Pass'),
  ('a64e340f-4002-5144-9a7a-0419e4aa8d5c', 5, 6090925584, 2107935102, '12th Pass'),
  ('7ded772e-2558-53ee-8b91-d4b0c10fafed', 2, 372253000, 17640000, 'Graduate'),
  ('63dd8ac0-7b24-591e-ac73-d5fbee9a12df', 2, NULL, NULL, '12th Pass'),
  ('4ca4c203-5ae3-5bc5-af0d-571f7ca46f64', 0, 499194993, 73942688, '8th Pass'),
  ('5a2746df-e35e-5c95-af2d-5d088c1f6dcb', 0, 89877066, 3674946, 'Graduate Professional'),
  ('c4a296f1-255c-51ed-bba0-b2f2eda0e2ae', 0, 356232853, 20000000, '10th Pass'),
  ('2900ae44-2cf0-544b-b6f1-3030cfaf3e53', 0, 279925752, 3500000, 'Graduate Professional'),
  ('b9137a24-d1b2-5c32-8ba5-58c60bfd8003', 0, 854614473, 209061621, 'Others'),
  ('61fdddc5-1ccc-594e-b1e7-9f0fe614e2e6', 2, 597813050, 14938300, 'Illiterate'),
  ('9a6bb722-aafe-58db-9729-c60d5cd336d0', 1, 44692890, 0, 'Graduate Professional'),
  ('b57d5de0-f382-5def-9682-85bf7c083f83', 1, 8595566, 13256000, 'Graduate Professional'),
  ('bada28ae-5923-59e7-af9e-a7b8c9d7525b', 0, NULL, NULL, '12th Pass'),
  ('11765cd0-161b-51d9-99c7-e5f4493a5f9e', 0, 100766534, 5591724, 'Others'),
  ('dbd460f7-4cce-5845-aa6a-9fddda865cce', 0, 35899797, 0, '12th Pass'),
  ('631b38d2-c374-576e-acaf-e5bf16aa1649', 4, 770050328, 167053709, '5th Pass'),
  ('dafc4f0d-ea94-550f-9670-9970f65385bf', 4, 71290900, 2911785, '10th Pass'),
  ('ddab1e50-b377-5716-a001-60c2bc1e60d5', 7, 56079827, 19554130, 'Others'),
  ('e2007674-4c26-52e6-ab6d-3954ceaf393e', 0, 323181661, 79652656, 'Post Graduate'),
  ('4faf15aa-e650-5ab8-b305-62deedaa93da', 2, 13438806, 1083540, 'Graduate'),
  ('f7330cfc-89d2-5016-bfa7-e5ce1023d8af', 0, 279925752, 3500000, 'Graduate Professional'),
  ('dab36c13-e93c-55c0-b7f9-87f58d09e1ad', 2, NULL, NULL, 'Graduate Professional'),
  ('1d413911-7c80-513b-8720-8b4fb9de9552', 1, 683378507, 3000000, 'Graduate'),
  ('8ccbf9b2-c015-5c56-8d72-8efeeda7e0a9', 2, 216446153, 147568332, 'Graduate'),
  ('7a5857c3-a256-5ce2-9be8-cb695a87a261', 0, 81780393, 13779730, '10th Pass')
) AS v(id, criminal_cases, assets, liabilities, education)
WHERE c.id = v.id::uuid;
UPDATE persons p SET education = COALESCE(p.education, v.education)
FROM (VALUES
  ('5ee6bf5f-b8b5-5792-b89c-f8951a977e09', 1, 96302813, 54117500, 'Graduate'),
  ('6531c581-e412-5bae-9ee9-5e1348482f47', 0, 277608000, 51332067, 'Post Graduate'),
  ('7567ec88-9d74-50bf-b5b0-f229ce599261', 0, 134341307, 20070580, 'Post Graduate'),
  ('2f2ca7e0-1bef-5f08-b7ee-2f8c186e4cc6', 0, 505816200, 34829246, '10th Pass'),
  ('e46235a5-bacf-51cc-ba1e-ab937fd9aaba', 0, 64247543, 10131539, '12th Pass'),
  ('cb881302-b776-5b92-aacc-44b3e49d6317', 11, 297620500, 2000000, '8th Pass'),
  ('a64e340f-4002-5144-9a7a-0419e4aa8d5c', 5, 6090925584, 2107935102, '12th Pass'),
  ('7ded772e-2558-53ee-8b91-d4b0c10fafed', 2, 372253000, 17640000, 'Graduate'),
  ('63dd8ac0-7b24-591e-ac73-d5fbee9a12df', 2, NULL, NULL, '12th Pass'),
  ('4ca4c203-5ae3-5bc5-af0d-571f7ca46f64', 0, 499194993, 73942688, '8th Pass'),
  ('5a2746df-e35e-5c95-af2d-5d088c1f6dcb', 0, 89877066, 3674946, 'Graduate Professional'),
  ('c4a296f1-255c-51ed-bba0-b2f2eda0e2ae', 0, 356232853, 20000000, '10th Pass'),
  ('2900ae44-2cf0-544b-b6f1-3030cfaf3e53', 0, 279925752, 3500000, 'Graduate Professional'),
  ('b9137a24-d1b2-5c32-8ba5-58c60bfd8003', 0, 854614473, 209061621, 'Others'),
  ('61fdddc5-1ccc-594e-b1e7-9f0fe614e2e6', 2, 597813050, 14938300, 'Illiterate'),
  ('9a6bb722-aafe-58db-9729-c60d5cd336d0', 1, 44692890, 0, 'Graduate Professional'),
  ('b57d5de0-f382-5def-9682-85bf7c083f83', 1, 8595566, 13256000, 'Graduate Professional'),
  ('bada28ae-5923-59e7-af9e-a7b8c9d7525b', 0, NULL, NULL, '12th Pass'),
  ('11765cd0-161b-51d9-99c7-e5f4493a5f9e', 0, 100766534, 5591724, 'Others'),
  ('dbd460f7-4cce-5845-aa6a-9fddda865cce', 0, 35899797, 0, '12th Pass'),
  ('631b38d2-c374-576e-acaf-e5bf16aa1649', 4, 770050328, 167053709, '5th Pass'),
  ('dafc4f0d-ea94-550f-9670-9970f65385bf', 4, 71290900, 2911785, '10th Pass'),
  ('ddab1e50-b377-5716-a001-60c2bc1e60d5', 7, 56079827, 19554130, 'Others'),
  ('e2007674-4c26-52e6-ab6d-3954ceaf393e', 0, 323181661, 79652656, 'Post Graduate'),
  ('4faf15aa-e650-5ab8-b305-62deedaa93da', 2, 13438806, 1083540, 'Graduate'),
  ('f7330cfc-89d2-5016-bfa7-e5ce1023d8af', 0, 279925752, 3500000, 'Graduate Professional'),
  ('dab36c13-e93c-55c0-b7f9-87f58d09e1ad', 2, NULL, NULL, 'Graduate Professional'),
  ('1d413911-7c80-513b-8720-8b4fb9de9552', 1, 683378507, 3000000, 'Graduate'),
  ('8ccbf9b2-c015-5c56-8d72-8efeeda7e0a9', 2, 216446153, 147568332, 'Graduate'),
  ('7a5857c3-a256-5ce2-9be8-cb695a87a261', 0, 81780393, 13779730, '10th Pass')
) AS v(id, criminal_cases, assets, liabilities, education)
JOIN candidates c ON c.id = v.id::uuid
WHERE p.id = c.person_id;

\endif
INSERT INTO seed_runs (name) VALUES ('seed_py_affidavits') ON CONFLICT (name) DO NOTHING;

COMMIT;

