-- Arunachal Pradesh parties: every party that fielded a Arunachal Pradesh VS candidate 2009-2024 (generated by scraper/src/bihar/generate-cli.ts).
-- Fill-only: existing rows (and admin edits) are never changed. Runs before the Arunachal Pradesh corrections and VS seeds.

INSERT INTO parties (id, name, abbreviation, color, eci_recognition) VALUES
  ('AAP', 'Aam Aadmi Party', NULL, '#0066FF', 'National'),
  ('AIP', 'All Indians Party', 'AIP', '#9CA3AF', 'Unrecognised'),
  ('ANCHDMCP', 'Arunachal Democratic Party', 'ANCHDMCP', '#9CA3AF', 'Unrecognised'),
  ('BJP', 'Bharatiya Janata Party', NULL, '#FF7A1A', 'National'),
  ('INC', 'Indian National Congress', NULL, '#38C6F4', 'National'),
  ('JDS', 'Janata Dal  (Secular)', NULL, '#228B22', NULL),
  ('JDU', 'Janata Dal  (United)', 'JD(U)', '#1FA37A', 'State'),
  ('LJPRV', 'Lok Janshakti Party(Ram Vilas)', NULL, '#3B8BFF', NULL),
  ('NCP', 'Nationalist Congress Party', NULL, '#006699', NULL),
  ('NPF', 'Naga Peoples Front', NULL, '#556B2F', NULL),
  ('NPP', 'National People''s Party', NULL, '#808080', 'National'),
  ('PPA', 'People''s Party of Arunachal', 'PPA', '#008000', 'State'),
  ('TMC', 'All India Trinamool Congress', NULL, '#00CC44', NULL)
ON CONFLICT (id) DO NOTHING;
