BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/logos/SHS.png', 'https://commons.wikimedia.org/wiki/File:Shiv_Sena_Flag.png', 'Soumava2002', 'CC BY 4.0'),
  ('/symbols/eci/SHS.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Bow_And_Arrow.svg', 'Abilngeorge', 'CC BY-SA 3.0'),
  ('/symbols/logos/SHSUBT.png', 'https://commons.wikimedia.org/wiki/File:SS(UBT)_flag.png', '456legend', 'CC BY-SA 4.0'),
  ('/symbols/eci/SHSUBT.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Flaming_Torch.png', 'Abilngeorge (credited on Commons to the Election Commission of India)', 'CC BY-SA 4.0'),
  ('/symbols/eci/NCP.png', 'https://commons.wikimedia.org/wiki/File:Clock_symbol_of_NCP.png', 'Atharvgairola692004', 'CC BY-SA 4.0'),
  ('/symbols/logos/MNS.jpg', 'https://commons.wikimedia.org/wiki/File:Maharashtra_Navnirman_Sena_Official_Flag.jpg', 'Maharashtra Navnirman Sena', 'Public domain (PD-textlogo)'),
  ('/symbols/eci/MNS.png', 'https://commons.wikimedia.org/wiki/File:Mns-symbol-railway-engine.png', 'Pratham Sawant', 'CC BY-SA 4.0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Maharashtra 2024 top parties, researched with sources (scraper/data/mh/
-- parties-2024.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_mh_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'SHS'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1966),
  leader_name = COALESCE(leader_name, 'Eknath Shinde'),
  headquarters = COALESCE(headquarters, 'Anand Ashram, Shree Bhavani Chowk, Tembhi Naka, Thane West, Maharashtra 400601'),
  website = COALESCE(website, 'https://shivsenacentraloffice.com'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Shiv_Sena_(Eknath_Shinde)'),
  description = COALESCE(description, 'A Marathi regionalist and Hindutva party founded by Bal Thackeray in Mumbai in June 1966; it first governed Maharashtra with the BJP in 1995, and under Uddhav Thackeray it led the Maha Vikas Aghadi government from 2019. Eknath Shinde''s revolt in June 2022 split the party, and in February 2023 the Election Commission awarded the Shiv Sena name and its bow-and-arrow symbol to Shinde''s faction, while Thackeray''s group became the Shiv Sena (UBT). In 2024, contesting in the BJP-led Mahayuti, it won 57 of 288 seats, and Shinde, Chief Minister since 2022, became Deputy Chief Minister.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#B8430B' ELSE color END
WHERE id = 'SHS';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'SS(UBT)'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2022),
  leader_name = COALESCE(leader_name, 'Uddhav Thackeray'),
  headquarters = COALESCE(headquarters, 'Shivsena Bhavan, Gadkari Chowk, Dadar, Mumbai, Maharashtra 400028'),
  website = COALESCE(website, 'https://shivsena.in'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Shiv_Sena_(UBT)'),
  description = COALESCE(description, 'The party of Uddhav Thackeray''s faction of the Shiv Sena, which the Election Commission named Shiv Sena (Uddhav Balasaheb Thackeray) and gave the flaming-torch symbol in October 2022, after Eknath Shinde''s revolt that June; in February 2023 the original name and bow-and-arrow went to Shinde''s faction. Thackeray had been Chief Minister from 2019 to 2022 at the head of the Maha Vikas Aghadi with the Congress and the NCP. In 2024, contesting in that alliance, it won 20 of 288 seats, and Aaditya Thackeray was elected leader of its legislators.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#F5B400' ELSE color END
WHERE id = 'SHSUBT';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'NCP'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1999),
  leader_name = COALESCE(leader_name, 'Ajit Pawar'),
  headquarters = COALESCE(headquarters, '79, North Avenue, New Delhi 110001'),
  website = COALESCE(website, 'https://ncponline.in'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Nationalist_Congress_Party'),
  description = COALESCE(description, 'Founded in June 1999 by Sharad Pawar, P. A. Sangma and Tariq Anwar after the Congress expelled them, the NCP governed Maharashtra with the Congress from 1999 to 2014 and joined the Maha Vikas Aghadi government in 2019. In July 2023 Ajit Pawar took most of its MLAs into the Shinde–BJP government, and in February 2024 the Election Commission awarded his faction the NCP name and clock symbol, while Sharad Pawar''s became the NCP (Sharadchandra Pawar). In 2024, in the Mahayuti, it won 41 of 288 seats to the Sharad Pawar party''s 10; after Ajit Pawar died in a plane crash in January 2026, Sunetra Pawar succeeded him as Deputy Chief Minister and party president.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#006699' ELSE color END
WHERE id = 'NCP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'MNS'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2006),
  leader_name = COALESCE(leader_name, 'Raj Thackeray'),
  headquarters = COALESCE(headquarters, 'Krishna Kunj, M. B. Raut Road, Shivaji Park, Mumbai, Maharashtra 400028'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Maharashtra_Navnirman_Sena'),
  description = COALESCE(description, 'A Marathi regionalist party founded in Mumbai on 9 March 2006 by Raj Thackeray after he left the Shiv Sena, then led by his cousin Uddhav Thackeray. It won 13 seats in its first assembly election in 2009, then one each in 2014 and 2019. In 2024 it contested 125 of the 288 seats outside both main alliances and won none, with about 1.6% of the vote.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#5F2301' ELSE color END
WHERE id = 'MNS';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_mh_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

