BEGIN;

INSERT INTO image_credits (url, source_url, author, licence) VALUES
  ('/symbols/logos/AGP.svg', 'https://commons.wikimedia.org/wiki/File:Asom_Gana_Parishad_flag_(1).svg', 'STMC2421', 'CC BY-SA 4.0'),
  ('/symbols/eci/AGP.svg', 'https://commons.wikimedia.org/wiki/File:Elephant_electoral_symbol.svg', 'Gnoeee', 'CC BY 4.0'),
  ('/symbols/logos/AIUDF.webp', 'https://commons.wikimedia.org/wiki/File:AIUDF_logo.webp', 'AIUDF, Guwahati', 'Public domain'),
  ('/symbols/eci/AIUDF.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Lock_And_Key.svg', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/logos/BOPF.svg', 'https://commons.wikimedia.org/wiki/File:BPF-Flag.svg', 'Rajuonline', 'Public domain'),
  ('/symbols/eci/BOPF.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Nangol.svg', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/logos/RJRD.jpg', 'https://commons.wikimedia.org/wiki/File:Raijor_Dal.jpg', 'Goswami21', 'CC BY-SA 4.0'),
  ('/symbols/eci/RJRD.jpg', 'https://commons.wikimedia.org/wiki/File:Gas_Cylinder.jpg', 'Faiznkm', 'CC BY-SA 4.0'),
  ('/symbols/logos/AJP.jpg', 'https://commons.wikimedia.org/wiki/File:AJP_FLAG.jpg', 'Goswami21', 'CC BY-SA 4.0'),
  ('/symbols/eci/AJP.png', 'https://commons.wikimedia.org/wiki/File:Indian_election_symbol_ship.png', 'XYZ 250706', 'CC BY-SA 4.0'),
  ('/symbols/eci/UPPL.png', 'https://commons.wikimedia.org/wiki/File:UPPL_Election_Symbol.png', 'Rraz4u', 'CC BY-SA 4.0'),
  ('/symbols/logos/JMM.svg', 'https://commons.wikimedia.org/wiki/File:Jharkhand_Mukti_Morcha_flag.svg', 'VNC200', 'CC BY-SA 4.0'),
  ('/symbols/eci/JMM.png', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Bow_And_Arrow.png', 'Abilngeorge', 'CC BY-SA 4.0'),
  ('/symbols/logos/AIFB.png', 'https://commons.wikimedia.org/wiki/File:AIFB_Flag_2026.png', 'XYZ 250706', 'CC0'),
  ('/symbols/eci/AIFB.svg', 'https://commons.wikimedia.org/wiki/File:Indian_Election_Symbol_Lion.svg', 'Abilngeorge', 'CC BY-SA 4.0')
ON CONFLICT (url) DO NOTHING;

-- Run once (seed_runs). Details of the Assam 2026 top parties, researched with sources (scraper/data/as/
-- parties-2026.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an
-- admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_as_party_profiles')
   AS seed_apply \gset
\if :seed_apply

UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AGP'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1985),
  leader_name = COALESCE(leader_name, 'Atul Bora'),
  headquarters = COALESCE(headquarters, 'Guwahati, Assam'),
  website = COALESCE(website, 'https://agpofficial.in/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Asom_Gana_Parishad'),
  description = COALESCE(description, 'An Assamese regionalist party formed in 1985 out of the Assam Movement after the Assam Accord, which governed the state twice under Prafulla Kumar Mahanta. In 2026 it contested 26 seats as a junior partner in the BJP-led NDA and won 10.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#99CCFF' ELSE color END
WHERE id = 'AGP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AIUDF'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2005),
  leader_name = COALESCE(leader_name, 'Badruddin Ajmal'),
  headquarters = COALESCE(headquarters, 'Guwahati, Assam'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/All_India_United_Democratic_Front'),
  description = COALESCE(description, 'An Assam party founded in 2005 by the businessman and cleric Badruddin Ajmal, drawing its support mainly from Bengali-origin Muslims. It fought the 2026 election outside both main alliances, contesting 30 seats and winning 2.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#348017' ELSE color END
WHERE id = 'AIUDF';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'BPF'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2005),
  leader_name = COALESCE(leader_name, 'Hagrama Mohilary'),
  headquarters = COALESCE(headquarters, 'Kokrajhar, Assam'),
  website = COALESCE(website, 'http://www.bpfassam.in/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Bodoland_People%27s_Front'),
  description = COALESCE(description, 'A Bodo regional party founded in 2005 by Hagrama Mohilary, based in the Bodoland Territorial Region, whose council it won back in 2025. It joined the BJP-led NDA for 2026 and won 10 of the 11 seats it contested.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FF6600' ELSE color END
WHERE id = 'BOPF';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'RD'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2020),
  leader_name = COALESCE(leader_name, 'Akhil Gogoi'),
  headquarters = COALESCE(headquarters, 'Guwahati, Assam'),
  website = COALESCE(website, 'http://www.raijordal.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Raijor_Dal'),
  description = COALESCE(description, 'An Assam party launched in 2020 by the peasant-rights activist Akhil Gogoi out of the Krishak Mukti Sangram Samiti and the anti-CAA movement. In 2026 it contested 13 seats in the Congress-led Asom Sonmilito Morcha and won 2, including Gogoi in Sibsagar.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FEE502' ELSE color END
WHERE id = 'RJRD';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AJP'),
  eci_recognition = COALESCE(eci_recognition, 'Unrecognised'),
  founded_year = COALESCE(founded_year, 2020),
  leader_name = COALESCE(leader_name, 'Lurinjyoti Gogoi'),
  headquarters = COALESCE(headquarters, 'Guwahati, Assam'),
  website = COALESCE(website, 'https://assamjatiyaparishad.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Assam_Jatiya_Parishad'),
  description = COALESCE(description, 'An Assamese regional party formed in 2020 by leaders of the All Assam Students Union and the AJYCP, with Lurinjyoti Gogoi as its first president. It contested 10 seats in the Congress-led Asom Sonmilito Morcha in 2026 and won none.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#0048BA' ELSE color END
WHERE id = 'AJP';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'UPPL'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 2015),
  leader_name = COALESCE(leader_name, 'Pramod Boro'),
  headquarters = COALESCE(headquarters, 'Kokrajhar, Assam'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/United_People%27s_Party_Liberal'),
  description = COALESCE(description, 'A Bodo regional party founded in 2015, based in the Bodoland Territorial Region and led by Pramod Boro. In 2026 it contested 18 seats outside the main alliances and won none.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#FAED09' ELSE color END
WHERE id = 'UPPL';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'JMM'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1972),
  leader_name = COALESCE(leader_name, 'Hemant Soren'),
  headquarters = COALESCE(headquarters, 'Ranchi, Jharkhand'),
  website = COALESCE(website, 'https://jmmparty.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/Jharkhand_Mukti_Morcha'),
  description = COALESCE(description, 'Jharkhand''s ruling party, founded in 1972 by Shibu Soren, Binod Bihari Mahato and A. K. Roy, which led the movement for a separate Jharkhand state. In Assam it contested 16 seats on its own in 2026, courting tea-garden Adivasi voters, and won none.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#337316' ELSE color END
WHERE id = 'JMM';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AITC'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1998),
  leader_name = COALESCE(leader_name, 'Mamata Banerjee'),
  headquarters = COALESCE(headquarters, 'Kolkata, West Bengal'),
  website = COALESCE(website, 'https://aitcofficial.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/All_India_Trinamool_Congress'),
  description = COALESCE(description, 'A West Bengal party founded in 1998 by Mamata Banerjee as a breakaway from the Congress, which ruled the state from 2011 until it lost the 2026 election to the BJP, winning 80 of the 291 seats it contested. After a post-poll split, the Election Commission froze its name and symbol in September 2026 and gave the Mamata Banerjee and rebel factions separate interim names.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#05472A' ELSE color END
WHERE id = 'TMC';
UPDATE parties SET name = regexp_replace(name, '\s+', ' ', 'g'),
  abbreviation = COALESCE(abbreviation, 'AIFB'),
  eci_recognition = COALESCE(eci_recognition, 'State'),
  founded_year = COALESCE(founded_year, 1939),
  leader_name = COALESCE(leader_name, 'G. Devarajan'),
  headquarters = COALESCE(headquarters, 'New Delhi, Delhi'),
  website = COALESCE(website, 'https://allindiaforwardbloc.org/'),
  wikipedia_url = COALESCE(wikipedia_url, 'https://en.wikipedia.org/wiki/All_India_Forward_Bloc'),
  description = COALESCE(description, 'A left-wing party founded by Subhas Chandra Bose in 1939 within the Congress, and a long-standing member of the Left Front in West Bengal. In 2026 it contested 24 seats in West Bengal as part of the Left Front and won none.'),
  color = CASE WHEN color IS NULL OR upper(color) IN ('#808080', '#9CA3AF') THEN '#AC1313' ELSE color END
WHERE id = 'AIFB';

\endif
INSERT INTO seed_runs (name) VALUES ('seed_as_party_profiles') ON CONFLICT (name) DO NOTHING;

COMMIT;

