BEGIN;

-- Run once (seed_runs). Moves parties the old manifests put in the wrong alliance (checked against the declared
-- alliance results). A move applies only while the party is still where the old manifest had it.
-- Generated by scraper/src/bihar/alliance-moves-cli.ts from scraper/data/alliance-moves-v1.json. Do not edit by hand.
SELECT NOT EXISTS (SELECT 1 FROM seed_runs WHERE name = 'seed_manifest_alliances_v1')
   AS seed_apply \gset
\if :seed_apply

-- JDS: UDF → LDF
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'UDF' THEN jsonb_set(al, '{parties}', (al->'parties') - 'JDS')
    WHEN al->>'id' = 'LDF' AND NOT (al->'parties') ? 'JDS' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('JDS'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232011' AND manifest_url::jsonb->'alliances' @> '[{"id":"UDF","parties":["JDS"]}]'::jsonb;
-- RSP: UDF → LDF
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'UDF' THEN jsonb_set(al, '{parties}', (al->'parties') - 'RSP')
    WHEN al->>'id' = 'LDF' AND NOT (al->'parties') ? 'RSP' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('RSP'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232011' AND manifest_url::jsonb->'alliances' @> '[{"id":"UDF","parties":["RSP"]}]'::jsonb;
-- NCP: UDF → LDF
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'UDF' THEN jsonb_set(al, '{parties}', (al->'parties') - 'NCP')
    WHEN al->>'id' = 'LDF' AND NOT (al->'parties') ? 'NCP' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('NCP'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232011' AND manifest_url::jsonb->'alliances' @> '[{"id":"UDF","parties":["NCP"]}]'::jsonb;
-- KRSP: LDF → UDF
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'LDF' THEN jsonb_set(al, '{parties}', (al->'parties') - 'KRSP')
    WHEN al->>'id' = 'UDF' AND NOT (al->'parties') ? 'KRSP' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('KRSP'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232011' AND manifest_url::jsonb->'alliances' @> '[{"id":"LDF","parties":["KRSP"]}]'::jsonb;
-- JPSS: LDF → UDF
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'LDF' THEN jsonb_set(al, '{parties}', (al->'parties') - 'JPSS')
    WHEN al->>'id' = 'UDF' AND NOT (al->'parties') ? 'JPSS' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('JPSS'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232011' AND manifest_url::jsonb->'alliances' @> '[{"id":"LDF","parties":["JPSS"]}]'::jsonb;
-- CMPKSC: LDF → UDF
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'LDF' THEN jsonb_set(al, '{parties}', (al->'parties') - 'CMPKSC')
    WHEN al->>'id' = 'UDF' AND NOT (al->'parties') ? 'CMPKSC' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('CMPKSC'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232011' AND manifest_url::jsonb->'alliances' @> '[{"id":"LDF","parties":["CMPKSC"]}]'::jsonb;
-- INCS: UDF → LDF
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'UDF' THEN jsonb_set(al, '{parties}', (al->'parties') - 'INCS')
    WHEN al->>'id' = 'LDF' AND NOT (al->'parties') ? 'INCS' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('INCS'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232016' AND manifest_url::jsonb->'alliances' @> '[{"id":"UDF","parties":["INCS"]}]'::jsonb;
-- KECST: UDF → LDF
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'UDF' THEN jsonb_set(al, '{parties}', (al->'parties') - 'KECST')
    WHEN al->>'id' = 'LDF' AND NOT (al->'parties') ? 'KECST' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('KECST'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232016' AND manifest_url::jsonb->'alliances' @> '[{"id":"UDF","parties":["KECST"]}]'::jsonb;
-- KEC: LDF → UDF
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'LDF' THEN jsonb_set(al, '{parties}', (al->'parties') - 'KEC')
    WHEN al->>'id' = 'UDF' AND NOT (al->'parties') ? 'KEC' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('KEC'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232021' AND manifest_url::jsonb->'alliances' @> '[{"id":"LDF","parties":["KEC"]}]'::jsonb;
-- RMPI: LDF → UDF
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'LDF' THEN jsonb_set(al, '{parties}', (al->'parties') - 'RMPI')
    WHEN al->>'id' = 'UDF' AND NOT (al->'parties') ? 'RMPI' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('RMPI'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232021' AND manifest_url::jsonb->'alliances' @> '[{"id":"LDF","parties":["RMPI"]}]'::jsonb;
-- INCS: UDF → LDF
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'UDF' THEN jsonb_set(al, '{parties}', (al->'parties') - 'INCS')
    WHEN al->>'id' = 'LDF' AND NOT (al->'parties') ? 'INCS' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('INCS'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'a7b8c9d0-e1f2-3456-0123-678901232021' AND manifest_url::jsonb->'alliances' @> '[{"id":"UDF","parties":["INCS"]}]'::jsonb;
-- PMK: ADMK → DMKALL
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'ADMK' THEN jsonb_set(al, '{parties}', (al->'parties') - 'PMK')
    WHEN al->>'id' = 'DMKALL' AND NOT (al->'parties') ? 'PMK' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('PMK'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'e5f6a7b8-c9d0-1234-ef01-456789012011' AND manifest_url::jsonb->'alliances' @> '[{"id":"ADMK","parties":["PMK"]}]'::jsonb;
-- AIFB: DMKALL → ADMK
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'DMKALL' THEN jsonb_set(al, '{parties}', (al->'parties') - 'AIFB')
    WHEN al->>'id' = 'ADMK' AND NOT (al->'parties') ? 'AIFB' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('AIFB'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'e5f6a7b8-c9d0-1234-ef01-456789012011' AND manifest_url::jsonb->'alliances' @> '[{"id":"DMKALL","parties":["AIFB"]}]'::jsonb;
-- SUCI: (none) → TMCALL
UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (
  SELECT jsonb_agg(CASE
    WHEN al->>'id' = 'TMCALL' AND NOT (al->'parties') ? 'SUCI' THEN jsonb_set(al, '{parties}', (al->'parties') || to_jsonb('SUCI'::text))
    ELSE al END ORDER BY ord)
  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text
WHERE id = 'd4e5f6a7-b8c9-0123-def0-345678901011' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(manifest_url::jsonb->'alliances') x WHERE x->'parties' ? 'SUCI');

\endif
INSERT INTO seed_runs (name) VALUES ('seed_manifest_alliances_v1') ON CONFLICT (name) DO NOTHING;

COMMIT;

