-- Goa parties: every party that fielded a Goa VS candidate 2012-2022 (generated by scraper/src/bihar/generate-cli.ts).
-- Fill-only: existing rows (and admin edits) are never changed. Runs before the Goa corrections and VS seeds.

INSERT INTO parties (id, name, abbreviation, color, eci_recognition) VALUES
  ('AAP', 'Aam Aadmi Party', NULL, '#0066FF', 'National'),
  ('AIMF', 'All India Minorities Front', 'AIMF', '#9CA3AF', 'Unrecognised'),
  ('APOI', 'Ambedkarite Party of India', NULL, '#808080', NULL),
  ('BJP', 'Bharatiya Janata Party', NULL, '#FF7A1A', 'National'),
  ('BMP1', 'Bahujan Mukti Party', NULL, '#808080', NULL),
  ('CPI', 'Communist Party of India', NULL, '#FF0000', NULL),
  ('CPIM', 'Communist Party of India  (Marxist)', NULL, '#B83A3E', 'National'),
  ('GFP', 'Goa Forward Party', 'GFP', '#9CA3AF', 'Unrecognised'),
  ('GOPRP', 'Goa Praja Party', 'GoPrP', '#9CA3AF', 'Unrecognised'),
  ('GSB', 'Goencho Swabhiman Party', 'GSB', '#9CA3AF', 'Unrecognised'),
  ('GSM', 'Goa Suraksha Manch', 'GSM', '#9CA3AF', 'Unrecognised'),
  ('GSRP', 'Goa Su-Raj Party', 'GSRP', '#9CA3AF', 'Unrecognised'),
  ('GVP', 'Goa Vikas Party', 'GVP', '#9CA3AF', 'Unrecognised'),
  ('INC', 'Indian National Congress', NULL, '#38C6F4', 'National'),
  ('JDU', 'Janata Dal  (United)', 'JD(U)', '#1FA37A', 'State'),
  ('JMBP', 'Jai Maha Bharath Party', NULL, '#808080', NULL),
  ('MAG', 'Maharashtrawadi Gomantak', 'MAG', '#9CA3AF', 'State'),
  ('NCP', 'Nationalist Congress Party', NULL, '#006699', NULL),
  ('NGRF', 'Niz Goenkar Revolution Front', 'NGRF', '#9CA3AF', 'Unrecognised'),
  ('RGP', 'Revolutionary Goans Party', NULL, '#808080', NULL),
  ('RPOIA', 'Republican Party of India (A)', NULL, '#808080', NULL),
  ('SAJPCS', 'Samajwadi Janata Party (ChandraShekhar)', 'SaJPCs', '#9CA3AF', 'Unrecognised'),
  ('SBBGP', 'Sambhaji Brigade Party', 'SBBGP', '#9CA3AF', 'Unrecognised'),
  ('SHS', 'Shiv Sena', NULL, '#FF6600', NULL),
  ('SJPR', 'Samajwadi Janata Party (Rashtriya)', 'SJP(R)', '#9CA3AF', 'Unrecognised'),
  ('SP', 'Samajwadi Party', NULL, '#E60000', NULL),
  ('TMC', 'All India Trinamool Congress', NULL, '#00CC44', NULL),
  ('UGDP', 'United Goans Democratic Party', 'UGDP', '#9CA3AF', 'Unrecognised'),
  ('UGP', 'United Goans Party', 'UGP', '#9CA3AF', 'Unrecognised')
ON CONFLICT (id) DO NOTHING;
