import type { ElectionJson, PartyEntry, SeatJson } from './types';
import type { ExistingSeed } from './existing-seed';
import { stableUuid, type SeatMatch } from './match';
import { runOnce } from '../seed-run-once';
import { q } from './sql';

export interface Plan { json: ElectionJson; seed: ExistingSeed; matches: SeatMatch[] }
const STATE_ID = 5;

export function seatMargin(seat: SeatJson): number {
  const v = seat.candidates.filter(c => c.partyId !== 'NOTA').map(c => c.votes).sort((a, b) => b - a);
  return (v[0] ?? 0) - (v[1] ?? 0);
}

export function candidateIds(plan: Plan): Map<string, { candidateId: string; resultId: string }> {
  const ids = new Map<string, { candidateId: string; resultId: string }>();
  plan.json.seats.forEach((seat, i) => {
    const byserial = new Map(plan.matches[i].matched.map(m => [m.serial, m.old]));
    for (const c of seat.candidates) {
      const old = byserial.get(c.serial);
      ids.set(`${seat.constNo}:${c.serial}`, old ? { candidateId: old.id, resultId: old.resultId }
        : { candidateId: stableUuid('bihar-vs', plan.json.year, seat.constNo, c.serial, 'candidate'), resultId: stableUuid('bihar-vs', plan.json.year, seat.constNo, c.serial, 'result') });
    }
  });
  return ids;
}

const values = (rows: string[]) => rows.join(',\n');

export function emitParties(parties: PartyEntry[]): string {
  const rows = [...parties].sort((a, b) => a.id.localeCompare(b.id))
    .map(p => `  (${q(p.id)}, ${q(p.name)}, ${q(p.abbreviation)}, ${q(p.color)}, ${q(p.recognition)})`);
  return [
    '-- Bihar parties: every party that fielded a Bihar VS candidate 2010-2025 (generated by scraper/src/bihar/generate-cli.ts).',
    '-- Fill-only: existing rows (and admin edits) are never changed. Runs before the Bihar corrections and VS seeds.',
    '',
    'INSERT INTO parties (id, name, abbreviation, color, eci_recognition) VALUES',
    values(rows),
    'ON CONFLICT (id) DO NOTHING;',
    '',
  ].join('\n');
}

export function emitYear(plan: Plan): string {
  const { json, seed } = plan;
  const ids = candidateIds(plan);
  const constIds = new Map(plan.matches.map((m, i) => [json.seats[i].constNo, m.constId]));
  const names = new Map(seed.constituencies.map(c => [c.id, c.name]));
  const consts: string[] = [], cands: string[] = [], results: string[] = [], genders: string[] = [];
  for (const seat of json.seats) {
    const cid = constIds.get(seat.constNo)!;
    consts.push(`  (${q(cid)}, ${q(json.electionId)}, NULL, ${STATE_ID}, ${q(names.get(cid)!)}, ${seat.constNo}, ${q(seat.type)}, ${seat.turnout}, ${seat.phase}, ${seat.electors})`);
    const margin = seatMargin(seat);
    for (const c of seat.candidates) {
      const id = ids.get(`${seat.constNo}:${c.serial}`)!;
      cands.push(`  (${q(id.candidateId)}, NULL, ${q(json.electionId)}, ${q(cid)}, ${q(c.partyId)}, ${q(c.name)}, FALSE, ${q(c.age)})`);
      results.push(`  (${q(id.resultId)}, ${q(id.candidateId)}, ${q(cid)}, ${c.votes}, ${q(c.status)}, ${margin}, 0, ${q(json.electionId)})`);
      if (c.sex) genders.push(`  (${q(id.candidateId)}, ${q(c.sex)})`);
    }
  }
  const total = json.seats.reduce((a, s) => a + s.candidates.length, 0);
  return [
    `-- Bihar Vidhan Sabha ${json.year}: every candidate + NOTA, real votes.`,
    `-- Source: ${json.source.title} (${json.source.url}), retrieved ${json.source.retrieved}.`,
    '-- Generated by scraper/src/bihar/generate-cli.ts from scraper/data/bihar/vs-' + json.year + '.json. Do not edit by hand.',
    '-- Existing DBs are brought to these values first by seed_bihar_corrections_v1.sql (runs before this file).',
    '-- One transaction: a failing statement leaves nothing half-applied (setup.sh stops on the first error).',
    '',
    'BEGIN;',
    '',
    seed.electionSql,
    '',
    `-- Constituencies (${json.seats.length})`,
    'INSERT INTO constituencies (id, election_id, district_id, state_id, name, const_no, type, voter_turnout, phase, total_electors) VALUES',
    values(consts),
    'ON CONFLICT DO NOTHING;',
    '',
    `-- Candidates (${total})`,
    'INSERT INTO candidates (id, person_id, election_id, const_id, party_id, name, is_incumbent, age) VALUES',
    values(cands),
    'ON CONFLICT DO NOTHING;',
    '',
    '-- Results (margin = seat margin on every row, NOTA excluded; the ingest rule)',
    'INSERT INTO results (id, candidate_id, const_id, votes, status, margin, round_no, election_id) VALUES',
    values(results),
    'ON CONFLICT DO NOTHING;',
    '',
    '-- Person gender from the ECI report, fill-only',
    'UPDATE persons p SET gender = v.sex',
    'FROM (VALUES',
    values(genders),
    ') AS v(candidate_id, sex)',
    'JOIN candidates c ON c.id = v.candidate_id::uuid',
    'WHERE p.id = c.person_id AND p.gender IS NULL;',
    '',
    ...(seed.manifestJson ? ['-- Manifest (only when none is published; admins edit it)',
      `UPDATE elections SET manifest_url = ${q(seed.manifestJson)} WHERE id = ${q(json.electionId)} AND manifest_url IS NULL;`, ''] : []),
    'COMMIT;',
    '',
  ].join('\n');
}

/**
 * Stops the corrections (the whole run-once transaction rolls back, setup.sh exits) when the DB holds Bihar candidates
 * the old seeds never had, or old-seed candidates whose party changed since: the matching was computed against the old
 * seeds, so such rows could make an UPDATE or a year-seed INSERT collide with the seat+party unique index.
 */
function preflight(plans: Plan[]): string[] {
  const old = plans.flatMap(p => p.seed.candidates.map(c => `  (${q(c.id)}, ${q(c.partyId)})`));
  const elections = plans.map(p => q(p.json.electionId)).join(', ');
  return [
    '-- Pre-flight: this DB must hold exactly the old seeds\' Bihar candidates, with their seeded parties.',
    'CREATE TEMP TABLE bihar_old_seed (id uuid PRIMARY KEY, party_id text) ON COMMIT DROP;',
    `INSERT INTO bihar_old_seed (id, party_id) VALUES\n${values(old)};`,
    'DO $$',
    'DECLARE unknown int; moved int;',
    'BEGIN',
    `  SELECT count(*) INTO unknown FROM candidates c WHERE c.election_id IN (${elections})`,
    '    AND NOT EXISTS (SELECT 1 FROM bihar_old_seed o WHERE o.id = c.id);',
    '  SELECT count(*) INTO moved FROM candidates c JOIN bihar_old_seed o ON o.id = c.id WHERE c.party_id IS DISTINCT FROM o.party_id;',
    '  IF unknown > 0 OR moved > 0 THEN',
    "    RAISE EXCEPTION 'seed_bihar_corrections_v1: % Bihar candidates are not in the old seeds and % changed party since; reconcile them first (docs/DEPLOYMENT.md 5.0a)', unknown, moved;",
    '  END IF;',
    'END $$;',
    '',
  ];
}

export function emitCorrections(plans: Plan[]): string {
  const body: string[] = [...preflight(plans)];
  for (const plan of plans) {
    const { json } = plan;
    const ids = candidateIds(plan);
    const deleted = plan.matches.flatMap(m => m.deleted.map(o => q(o.id)));
    const res: string[] = [], cand: string[] = [], cons: string[] = [];
    plan.json.seats.forEach((seat, i) => {
      const margin = seatMargin(seat);
      cons.push(`  (${q(plan.matches[i].constId)}, ${q(seat.type)}, ${seat.electors}, ${seat.turnout}, ${seat.phase})`);
      for (const m of plan.matches[i].matched) {
        const c = seat.candidates.find(x => x.serial === m.serial)!;
        res.push(`  (${q(ids.get(`${seat.constNo}:${c.serial}`)!.resultId)}, ${c.votes}, ${q(c.status)}, ${margin})`);
        cand.push(`  (${q(m.old.id)}, ${q(c.name)}, ${q(c.partyId)}, ${q(c.age)}, ${q(m.old.name)})`);
      }
    });
    body.push(`-- ${json.year}`);
    if (deleted.length) {
      body.push(`DELETE FROM results WHERE candidate_id IN (${deleted.join(', ')});`);
      body.push(`DELETE FROM candidates WHERE id IN (${deleted.join(', ')});`);
    }
    body.push(
      'UPDATE results r SET votes = v.votes, status = v.status::result_status, margin = v.margin',
      `FROM (VALUES\n${values(res)}\n) AS v(id, votes, status, margin) WHERE r.id = v.id::uuid;`,
      // persons first (they compare against the old candidate name), then candidates
      'UPDATE persons p SET name = v.name',
      `FROM (VALUES\n${values(cand)}\n) AS v(id, name, party_id, age, old_name)`,
      'JOIN candidates c ON c.id = v.id::uuid',
      'WHERE p.id = c.person_id AND p.name = v.old_name AND v.name <> v.old_name',
      '  AND (SELECT count(*) FROM candidates c2 WHERE c2.person_id = p.id) = 1;',
      'UPDATE candidates c SET name = v.name, party_id = v.party_id, age = v.age::smallint',
      `FROM (VALUES\n${values(cand)}\n) AS v(id, name, party_id, age, old_name) WHERE c.id = v.id::uuid;`,
      'UPDATE constituencies k SET type = v.type::constituency_type, total_electors = v.electors, voter_turnout = v.turnout, phase = v.phase::smallint',
      `FROM (VALUES\n${values(cons)}\n) AS v(id, type, electors, turnout, phase) WHERE k.id = v.id;`,
      '',
    );
  }
  return runOnce({
    name: 'seed_bihar_corrections_v1',
    comment: [
      'Run once (seed_runs). Brings the Bihar VS 2010-2025 rows of an existing DB to the real ECI values before the',
      'Bihar VS seeds run: deletes the old rows ECI does not have (decided in scraper/data/bihar/decisions.json),',
      'fixes votes/status/margin, candidate names/party/age, constituency type/electors/turnout/phase, and renames',
      'auto-created single-candidacy persons still carrying the old name. The VS seeds then insert the missing',
      'candidates. On a fresh DB there are no Bihar rows yet: the body is skipped and only the marker is written.',
      'Generated by scraper/src/bihar/generate-cli.ts. Do not edit by hand.',
    ],
    conditions: [`EXISTS (SELECT 1 FROM constituencies WHERE election_id = ${q(plans[0].json.electionId)})`],
    body,
  }).join('\n');
}

/** Ids whose row (constituency, candidate or result tuple) exists in both seeds with different values. */
export function changedRows(oldSql: string, newSql: string): string[] {
  const rows = (sql: string) => {
    const out = new Map<string, string>();
    let table = '';
    for (const l of sql.split('\n')) {
      const ins = /^INSERT INTO (\w+) /.exec(l);
      if (ins) { table = ins[1]; continue; }
      if (!/^  \('/.test(l)) { if (!l.startsWith('  (')) table = ''; continue; }
      if (table) out.set(`${table}:${l.slice(4, l.indexOf("'", 4))}`, l.replace(/,$/, ''));
    }
    return out;
  };
  const before = rows(oldSql);
  return [...rows(newSql)].filter(([k, line]) => before.has(k) && before.get(k) !== line).map(([k]) => k.split(':')[1]);
}
