import type { RunOnceSeed } from '../seed-run-once';
import { runOnce } from '../seed-run-once';
import { normName } from './names';
import { q } from './sql';

export interface Candidacy { candidateId: string; year: number; constNo: number; name: string; partyId: string }
export interface LinkGroup { key: string; confidence: 'high' | 'medium' | 'review'; members: Candidacy[] }

export const COMMON_NAMES = new Set([
  'ANIL KUMAR', 'SUNIL KUMAR', 'RAJESH KUMAR', 'RAMESH KUMAR', 'MANOJ KUMAR', 'VIJAY KUMAR', 'SANJAY KUMAR', 'AJAY KUMAR',
  'RAJU KUMAR', 'MUKESH KUMAR', 'RAKESH KUMAR', 'SANTOSH KUMAR', 'ASHOK KUMAR', 'DINESH KUMAR', 'PANKAJ KUMAR', 'AMIT KUMAR',
  'RAVI KUMAR', 'MOHD ANWAR', 'RAM KUMAR', 'SHIV KUMAR',
]);

export const linkKey = (name: string) => normName(name.replace(/\s+(alias|urf|@)\s+.*$/i, '')).replace(/[0-9]/g, '').replace(/\s+/g, ' ').trim();

export function groupCandidacies(all: Candidacy[]): LinkGroup[] {
  const groups = new Map<string, Candidacy[]>();
  for (const x of all) {
    if (x.partyId === 'NOTA') continue;
    const key = `${linkKey(x.name)}|${x.constNo}`;
    groups.set(key, [...(groups.get(key) ?? []), x]);
  }
  const out: LinkGroup[] = [];
  for (const [key, members] of groups) {
    const years = new Set(members.map(m => m.year));
    if (years.size < 2) continue;
    const name = key.split('|')[0];
    const parties = new Set(members.map(m => m.partyId));
    const common = COMMON_NAMES.has(name);
    const review = years.size !== members.length || (common && (parties.size > 1 || parties.has('IND')));
    out.push({ key, confidence: review ? 'review' : parties.size === 1 ? 'high' : 'medium', members: [...members].sort((a, b) => a.year - b.year) });
  }
  return out.sort((a, b) => a.key.localeCompare(b.key));
}

export function emitLinksSeed(groups: LinkGroup[]): string {
  const linked = groups.filter(g => g.confidence !== 'review');
  const rows = linked.flatMap((g, i) => g.members.map(m => `(${i + 1}, ${q(m.candidateId)})`));
  const seed: RunOnceSeed = {
    name: 'seed_bihar_person_links_v2',
    comment: [
      'Run once (seed_runs). Links the same politician across Bihar VS 2010-2025 (same name, same seat, two or more',
      'years; generated by scraper/src/bihar/links-cli.ts from the ECI data). Each group anchors on its most-linked',
      'person; only candidates whose person is an auto-created single-candidacy person outside the merge log move,',
      'so curated persons and admin merges/splits are never undone. The orphan trigger deletes the emptied persons.',
    ],
    body: [
      'CREATE TEMP TABLE link_groups (g int, cid uuid) ON COMMIT DROP;',
      `INSERT INTO link_groups (g, cid) VALUES\n${rows.join(', ')};`,
      'WITH members AS (',
      '  SELECT lg.g, c.id AS cid, c.person_id AS pid, (SELECT count(*) FROM candidates c2 WHERE c2.person_id = c.person_id) AS n',
      '  FROM link_groups lg JOIN candidates c ON c.id = lg.cid',
      '), anchor AS (',
      '  SELECT DISTINCT ON (g) g, pid FROM members ORDER BY g, n DESC, cid',
      ')',
      'UPDATE candidates c SET person_id = a.pid',
      'FROM members m JOIN anchor a ON a.g = m.g',
      'WHERE c.id = m.cid AND m.pid <> a.pid AND m.n = 1',
      "  AND NOT EXISTS (SELECT 1 FROM person_merges pm WHERE pm.duplicate->>'id' = m.pid::text OR pm.keeper_ref = m.pid);",
    ],
  };
  return runOnce(seed).join('\n');
}
