/**
 * Party ids in old manifests that the ECI data does not use (scraper/data/<slug>/manifest-party-fixes.json:
 * year → { old id: new id }), e.g. Kerala 2011's "MUL" where every IUML candidate is now IUML.
 * Manifests are written only while none is published, so existing DBs get the fix from a run-once seed.
 */
import { runOnce } from '../seed-run-once';
import type { ElectionJson } from './types';

export type ManifestFixes = Record<string, string>;

/** Alliance party ids (after the fixes) that no candidate of the election has. */
export function alliancePartyGaps(manifestJson: string | null, json: ElectionJson, fixes: ManifestFixes): string[] {
  if (!manifestJson) return [];
  const used = new Set(json.seats.flatMap(s => s.candidates.map(c => c.partyId)));
  const alliances: { parties?: string[] }[] = JSON.parse(manifestJson).alliances ?? [];
  return alliances.flatMap(a => a.parties ?? []).map(id => fixes[id] ?? id).filter(id => !used.has(id));
}

/** A run-once seed replacing the quoted old ids in each election's manifest (alliances and leaders alike). */
export function emitManifestFixes(name: string, stateName: string, elections: { electionId: string; year: number; fixes: ManifestFixes }[]): string {
  const body = elections.flatMap(e => Object.entries(e.fixes).map(([from, to]) =>
    `UPDATE elections SET manifest_url = replace(manifest_url, '"${from}"', '"${to}"') WHERE id = '${e.electionId}';`));
  return runOnce({
    name,
    comment: [
      `Run once (seed_runs). Points the ${stateName} manifests at the party ids the ECI data uses (a published manifest is`,
      'never rewritten by the year seeds). Generated by scraper/src/bihar/generate-cli.ts from',
      'scraper/data/<state>/manifest-party-fixes.json. Do not edit by hand.',
    ],
    body,
  }).join('\n') + '\n';
}

/** One alliance-membership correction: `party` leaves `from` (null: it was in no alliance) and joins `to`. */
export interface AllianceMove { electionId: string; party: string; from: string | null; to: string }

/**
 * A run-once seed moving parties between a manifest's alliances (old manifests had some parties in the wrong one).
 * Each move applies only while the manifest still has the party where the old manifest put it, so an admin's later
 * edit is never overwritten.
 */
export function emitAllianceMoves(name: string, moves: AllianceMove[]): string {
  const body = moves.map(m => {
    const p = `'${m.party}'`;
    const parties = `(al->'parties')`;
    const set = [
      `UPDATE elections SET manifest_url = jsonb_set(manifest_url::jsonb, '{alliances}', (`,
      `  SELECT jsonb_agg(CASE`,
      ...(m.from ? [`    WHEN al->>'id' = '${m.from}' THEN jsonb_set(al, '{parties}', ${parties} - ${p})`] : []),
      `    WHEN al->>'id' = '${m.to}' AND NOT ${parties} ? ${p} THEN jsonb_set(al, '{parties}', ${parties} || to_jsonb(${p}::text))`,
      `    ELSE al END ORDER BY ord)`,
      `  FROM jsonb_array_elements(manifest_url::jsonb->'alliances') WITH ORDINALITY x(al, ord)))::text`,
    ];
    const where = m.from
      ? `WHERE id = '${m.electionId}' AND manifest_url::jsonb->'alliances' @> '${JSON.stringify([{ id: m.from, parties: [m.party] }])}'::jsonb;`
      : `WHERE id = '${m.electionId}' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(manifest_url::jsonb->'alliances') x WHERE x->'parties' ? ${p});`;
    return [`-- ${m.party}: ${m.from ?? '(none)'} → ${m.to}`, ...set, where].join('\n');
  });
  return runOnce({
    name,
    comment: [
      'Run once (seed_runs). Moves parties the old manifests put in the wrong alliance (checked against the declared',
      'alliance results). A move applies only while the party is still where the old manifest had it.',
      'Generated by scraper/src/bihar/alliance-moves-cli.ts from scraper/data/alliance-moves-v1.json. Do not edit by hand.',
    ],
    body,
  }).join('\n') + '\n';
}
