/**
 * Party ids in old manifests that the ECI data does not use (scraper/data/<slug>/manifest-party-fixes.json:
 * year → { old id: new id }), e.g. Kerala 2011's "MUL" where every IUML candidate is now IUML.
 * Manifests are written only while none is published, so existing DBs get the fix from a run-once seed.
 */
import { runOnce } from '../seed-run-once';
import type { ElectionJson } from './types';

export type ManifestFixes = Record<string, string>;

/** Alliance party ids (after the fixes) that no candidate of the election has. */
export function alliancePartyGaps(manifestJson: string | null, json: ElectionJson, fixes: ManifestFixes): string[] {
  if (!manifestJson) return [];
  const used = new Set(json.seats.flatMap(s => s.candidates.map(c => c.partyId)));
  const alliances: { parties?: string[] }[] = JSON.parse(manifestJson).alliances ?? [];
  return alliances.flatMap(a => a.parties ?? []).map(id => fixes[id] ?? id).filter(id => !used.has(id));
}

/** A run-once seed replacing the quoted old ids in each election's manifest (alliances and leaders alike). */
export function emitManifestFixes(name: string, stateName: string, elections: { electionId: string; year: number; fixes: ManifestFixes }[]): string {
  const body = elections.flatMap(e => Object.entries(e.fixes).map(([from, to]) =>
    `UPDATE elections SET manifest_url = replace(manifest_url, '"${from}"', '"${to}"') WHERE id = '${e.electionId}';`));
  return runOnce({
    name,
    comment: [
      `Run once (seed_runs). Points the ${stateName} manifests at the party ids the ECI data uses (a published manifest is`,
      'never rewritten by the year seeds). Generated by scraper/src/bihar/generate-cli.ts from',
      'scraper/data/<state>/manifest-party-fixes.json. Do not edit by hand.',
    ],
    body,
  }).join('\n') + '\n';
}
