/**
 * Bihar 2025 top parties (won a seat, 1 %+ of the vote, or alliance member): details researched with sources in
 * scraper/data/bihar/parties-2025.json (user-reviewed), emitted as a run-once fill-only seed. Party images live in
 * frontend/public/symbols and are wired by seed_party_symbols.sql (which runs every deploy); this seed credits them.
 */
import { runOnce } from '../seed-run-once';
import { q } from './sql';

export interface ImageSource { file: string; commons: string; source_url: string; author: string | null; licence: string }
export interface PartyProfile {
  id: string; name: string; abbreviation: string | null; eci_recognition: 'National' | 'State' | 'Unrecognised' | null;
  founded_year: number | null; leader_name: string | null; headquarters: string | null; website: string | null; wikipedia_url: string | null;
  color: string | null; description: string | null; eci_symbol: string | null; sources: string[];
  logo: ImageSource | null; eci_image: ImageSource | null;
  current_logo_ok?: boolean | null; current_eci_ok?: boolean | null;
}
/** Served paths of the images approved in review, per party. */
export type ApprovedImages = Record<string, { logo?: string; eci?: string }>;
/** Old image paths found wrong in review with no replacement: cleared once, only while still set. */
export type RemovedImages = Record<string, { logo?: string; eci?: string }>;

/** Colours the seeds use as placeholders; only these are replaced by a researched colour. */
const PLACEHOLDER_COLORS = ['#808080', '#9CA3AF'];

/** A party's current image path in seed_party_symbols.sql (the column name must start a SET item, not end another). */
export function currentPath(seed: string, id: string, col: 'symbol_url' | 'eci_symbol_url'): string | null {
  const line = new RegExp(`^UPDATE parties SET (.*) WHERE id = '${id}';$`, 'm').exec(seed)?.[1];
  if (!line) return null;
  return new RegExp(`(?:^|, )${col} = '([^']+)'`).exec(line)?.[1] ?? null;
}

export function symbolsSeedLine(id: string, logo: string | null, eci: string | null): string | null {
  const set = [logo ? `symbol_url = ${q(logo)}` : null, eci ? `eci_symbol_url = ${q(eci)}` : null].filter(Boolean);
  return set.length ? `UPDATE parties SET ${set.join(', ')} WHERE id = ${q(id)};` : null;
}

export function emitPartyProfilesSeed(profiles: PartyProfile[], approved: ApprovedImages, removed: RemovedImages = {}): string {
  const credits: string[] = [];
  for (const p of profiles) {
    const a = approved[p.id] ?? {};
    if (a.logo && p.logo) credits.push(`  (${q(a.logo)}, ${q(p.logo.source_url)}, ${q(p.logo.author)}, ${q(p.logo.licence)})`);
    if (a.eci && p.eci_image) credits.push(`  (${q(a.eci)}, ${q(p.eci_image.source_url)}, ${q(p.eci_image.author)}, ${q(p.eci_image.licence)})`);
  }
  const body = profiles.map(p => {
    const fill = (col: string, v: string | number | null) => (v === null || v === undefined ? null : `${col} = COALESCE(${col}, ${q(v)})`);
    const set = [
      `name = regexp_replace(name, '\\s+', ' ', 'g')`,
      fill('abbreviation', p.abbreviation), fill('eci_recognition', p.eci_recognition), fill('founded_year', p.founded_year),
      fill('leader_name', p.leader_name), fill('headquarters', p.headquarters), fill('website', p.website),
      fill('wikipedia_url', p.wikipedia_url), fill('description', p.description),
      p.color ? `color = CASE WHEN color IS NULL OR upper(color) IN (${PLACEHOLDER_COLORS.map(q).join(', ')}) THEN ${q(p.color)} ELSE color END` : null,
    ].filter(Boolean);
    return `UPDATE parties SET ${set.join(',\n  ')}\nWHERE id = ${q(p.id)};`;
  });
  for (const [id, r] of Object.entries(removed)) {
    if (r.logo) body.push(`UPDATE parties SET symbol_url = NULL WHERE id = ${q(id)} AND symbol_url = ${q(r.logo)};`);
    if (r.eci) body.push(`UPDATE parties SET eci_symbol_url = NULL WHERE id = ${q(id)} AND eci_symbol_url = ${q(r.eci)};`);
  }
  return runOnce({
    name: 'seed_bihar_party_profiles',
    comment: [
      'Run once (seed_runs). Details of the Bihar 2025 top parties, researched with sources (scraper/data/bihar/',
      'parties-2025.json, user-reviewed), generated by scraper/src/bihar/party-profiles-cli.ts. Fill-only: a field an',
      'admin set is never overwritten; colour replaces only the grey placeholder. Image credits above the guard are idempotent.',
    ],
    always: credits.length ? ['INSERT INTO image_credits (url, source_url, author, licence) VALUES', credits.join(',\n'), 'ON CONFLICT (url) DO NOTHING;'] : [],
    body,
  }).join('\n');
}
