/**
 * Bihar 2025 candidate photos from the ECI results site: the top candidates of each seat (by votes) get the photo ECI
 * showed on its candidate-wise results page, stored once in our Blob store and credited to ECI. Older elections have
 * no ECI photos; a person who also ran in 2025 shows that photo on every contest.
 */
import type { CandidateDetail } from '../adapters/eci-vs-adapter';
import { runOnce } from '../seed-run-once';
import { similarity } from './names';
import { q } from './sql';
import type { CandidateJson, SeatJson } from './types';

/** Candidates per seat that get a photo (winner, runner-up, 3rd, 4th). */
export const TOP_PER_SEAT = 4;

/** ECI photo → 240×300 JPEG (~7 KB), the size every candidate photo is hosted at. */
export async function shrinkPhoto(raw: Buffer): Promise<Buffer> {
  const sharp = (await import('sharp')).default;
  return sharp(raw).rotate().resize({ width: 240, height: 300, fit: 'cover', position: 'top' }).jpeg({ quality: 78, mozjpeg: true }).toBuffer();
}
/** ECI publishes these photos without a stated licence; the credit says so. */
export const ECI_CREDIT = { author: 'Election Commission of India', licence: 'ECI results website (no licence stated)' };

const NAME_WITH_VOTES = 0.5;
const NAME_ONLY = 0.8;

export function topCandidates(seat: SeatJson, n = TOP_PER_SEAT): CandidateJson[] {
  return seat.candidates.filter(c => c.partyId !== 'NOTA').sort((a, b) => b.votes - a.votes).slice(0, n);
}

/** The ECI photo of a candidate: same votes and a plausible name, else one clearly matching name. */
export function matchPhoto(c: CandidateJson, eci: CandidateDetail[]): string | null {
  const byVotes = eci.find(e => e.votes === c.votes && similarity(e.name, c.name) >= NAME_WITH_VOTES);
  if (byVotes) return byVotes.photo;
  const byName = eci.filter(e => similarity(e.name, c.name) >= NAME_ONLY);
  return byName.length === 1 ? byName[0].photo : null;
}

export interface PhotoRow { candidateId: string; url: string; sourceUrl: string }

export interface PhotosSeedOpts { seedName: string; label: string }
export const BIHAR_PHOTOS: PhotosSeedOpts = { seedName: 'seed_bihar_candidate_photos', label: 'Bihar 2025' };

export function emitPhotosSeed(rows: PhotoRow[], opts: PhotosSeedOpts = BIHAR_PHOTOS): string {
  const values = rows.map(r => `  (${q(r.candidateId)}, ${q(r.url)})`).join(',\n');
  return runOnce({
    name: opts.seedName,
    comment: [
      `Run once (seed_runs). ${opts.label} top-4 candidates' photos from the ECI results site, hosted in our Blob store,`,
      'generated by scraper/src/bihar/photos-cli.ts. Fill-only: a photo already set (leaders, admin uploads) is kept.',
      'The image credits above the guard are idempotent and run every time.',
    ],
    always: rows.length ? [
      'INSERT INTO image_credits (url, source_url, author, licence) VALUES',
      rows.map(r => `  (${q(r.url)}, ${q(r.sourceUrl)}, ${q(ECI_CREDIT.author)}, ${q(ECI_CREDIT.licence)})`).join(',\n'),
      'ON CONFLICT (url) DO NOTHING;',
    ] : [],
    body: rows.length ? [
      'UPDATE persons p SET photo_url = COALESCE(p.photo_url, v.url)',
      `FROM (VALUES\n${values}\n) AS v(id, url)`,
      'JOIN candidates c ON c.id = v.id::uuid',
      'WHERE p.id = c.person_id;',
    ] : [],
  }).join('\n');
}
