/**
 * A state's districts and regions seed (seed_<slug>_districts_regions.sql) from a sourced scraper/data/<slug>/districts.json:
 * districts and regions inserted fill-only, then every seat of the given elections tagged by its seat number. Idempotent;
 * scoped to those elections (Lok Sabha and other delimitations never touched).
 */
import { q } from './sql';
import { STATES, StateCode, electionsOf } from './elections';

export interface StateRegions {
  stateId: number; stateName: string; seatCount: number;
  districts: { code: string; name: string }[];
  regions: { code: string; name: string; districts: string[] }[];
  /** Seat number → district code. */
  seats: Record<number, string>;
  /** Seat number → region code, when regions do not follow districts (Delhi: Lok Sabha seats). */
  seatRegions?: Record<number, string>;
  electionIds: string[];
}

export function emitStateRegions(o: StateRegions): string {
  const districts = new Set(o.districts.map(d => d.code));
  const regionOf = new Map<string, string>();
  for (const r of o.regions) for (const d of r.districts) regionOf.set(d, r.code);
  const regionCodes = new Set(o.regions.map(r => r.code));
  if (!o.seatRegions) for (const d of districts) if (!regionOf.has(d)) throw new Error(`${d} is in no region`);
  const regionOfSeat = (no: number, d: string): string => {
    if (!o.seatRegions) return regionOf.get(d)!;
    const r = o.seatRegions[no];
    if (!r) throw new Error(`seat ${no} has no region`);
    if (!regionCodes.has(r)) throw new Error(`${r} is not a region`);
    return r;
  };
  const ids = o.electionIds.map(q).join(', ');
  const updates: string[] = [];
  for (let no = 1; no <= o.seatCount; no++) {
    const d = o.seats[no];
    if (!d) throw new Error(`seat ${no} has no district`);
    if (!districts.has(d)) throw new Error(`${d} is not a district`);
    updates.push(`UPDATE constituencies SET district_id = (SELECT id FROM districts WHERE code = ${q(d)}), region_id = (SELECT id FROM regions WHERE state_id = ${o.stateId} AND code = ${q(regionOfSeat(no, d))}) WHERE election_id IN (${ids}) AND const_no = ${no};`);
  }
  return [
    `-- ${o.stateName}: districts, regions and seat assignments (generated by scraper/src/bihar/regions-cli.ts from the sourced`,
    `-- scraper/data/<slug>/districts.json). Runs after the ${o.stateName} VS seeds; idempotent; scoped to those elections.`,
    '',
    ...o.districts.map(d => `INSERT INTO districts (state_id, name, code) VALUES (${o.stateId}, ${q(d.name)}, ${q(d.code)}) ON CONFLICT (code) DO NOTHING;`),
    ...o.regions.map(r => `INSERT INTO regions (state_id, name, code) VALUES (${o.stateId}, ${q(r.name)}, ${q(r.code)}) ON CONFLICT (state_id, code) DO NOTHING;`),
    '',
    ...updates,
    '',
  ].join('\n');
}

/**
 * A state's boundary sets in its data dir: `districts.json` is the 2008 set; a state whose elections span redraws
 * (J&K: 1995 and 2022) has one `districts-<era>.json` per set. Each set is scoped to that era's elections and seats.
 */
export function regionSets(code: StateCode, files: string[]): { file: string; delimitation: string; seatCount: number; electionIds: string[] }[] {
  const sets = files.flatMap(file => {
    const m = /^districts(?:-(\d{4}))?\.json$/.exec(file);
    if (!m) return [];
    const delimitation = m[1] ?? '2008';
    const elections = electionsOf(code).filter(e => e.newElection?.delimitation === delimitation);
    if (!elections.length) throw new Error(`${file}: no ${code} election on the ${delimitation} boundaries`);
    return [{ file, delimitation, seatCount: elections[0].seats ?? STATES[code].seats, electionIds: elections.map(e => e.electionId) }];
  }).sort((a, b) => a.delimitation.localeCompare(b.delimitation));
  // Writing a seed from no file would empty a shipped one (BR/WB/TN/KL/PY keep their seeds without a districts file).
  if (!sets.length) throw new Error(`${code}: no districts.json or districts-<era>.json in its data dir`);
  return sets;
}
