/**
 * A state's districts and regions seed (seed_<slug>_districts_regions.sql) from a sourced scraper/data/<slug>/districts.json:
 * districts and regions inserted fill-only, then every seat of the given elections tagged by its seat number. Idempotent;
 * scoped to those elections (Lok Sabha and other delimitations never touched).
 */
import { q } from './sql';

export interface StateRegions {
  stateId: number; stateName: string; seatCount: number;
  districts: { code: string; name: string }[];
  regions: { code: string; name: string; districts: string[] }[];
  /** Seat number → district code. */
  seats: Record<number, string>;
  electionIds: string[];
}

export function emitStateRegions(o: StateRegions): string {
  const districts = new Set(o.districts.map(d => d.code));
  const regionOf = new Map<string, string>();
  for (const r of o.regions) for (const d of r.districts) regionOf.set(d, r.code);
  for (const d of districts) if (!regionOf.has(d)) throw new Error(`${d} is in no region`);
  const ids = o.electionIds.map(q).join(', ');
  const updates: string[] = [];
  for (let no = 1; no <= o.seatCount; no++) {
    const d = o.seats[no];
    if (!d) throw new Error(`seat ${no} has no district`);
    if (!districts.has(d)) throw new Error(`${d} is not a district`);
    updates.push(`UPDATE constituencies SET district_id = (SELECT id FROM districts WHERE code = ${q(d)}), region_id = (SELECT id FROM regions WHERE state_id = ${o.stateId} AND code = ${q(regionOf.get(d)!)}) WHERE election_id IN (${ids}) AND const_no = ${no};`);
  }
  return [
    `-- ${o.stateName}: districts, regions and seat assignments (generated by scraper/src/bihar/regions-cli.ts from the sourced`,
    `-- scraper/data/<slug>/districts.json). Runs after the ${o.stateName} VS seeds; idempotent; scoped to those elections.`,
    '',
    ...o.districts.map(d => `INSERT INTO districts (state_id, name, code) VALUES (${o.stateId}, ${q(d.name)}, ${q(d.code)}) ON CONFLICT (code) DO NOTHING;`),
    ...o.regions.map(r => `INSERT INTO regions (state_id, name, code) VALUES (${o.stateId}, ${q(r.name)}, ${q(r.code)}) ON CONFLICT (state_id, code) DO NOTHING;`),
    '',
    ...updates,
    '',
  ].join('\n');
}
