/**
 * seed_as_2026_districts_regions.sql: Assam 2026 seats (2023 delimitation) → district and region. The 2008-era Assam
 * seed tags by seat-number ranges, which do not apply to the redrawn seats, so each 2026 seat is tagged by its own row.
 */
export function emitRegions2026(rows: { constNo: number; district: string }[], districtRegion: Record<string, string>, electionId: string): string {
  const lines = rows.map(r => {
    const region = districtRegion[r.district];
    if (!region) throw new Error(`${r.district} has no region`);
    return `UPDATE constituencies SET district_id = (SELECT id FROM districts WHERE code = '${r.district}'), region_id = (SELECT id FROM regions WHERE code = '${region}') WHERE election_id = '${electionId}' AND const_no = ${r.constNo};`;
  });
  return [
    '-- Assam 2026 (2023 delimitation): each seat\'s district and region. Generated by scraper/src/bihar/regions-2026-cli.ts',
    '-- from scraper/data/as/districts-2026.json (sourced). Districts and regions come from seed_as_districts_regions.sql,',
    '-- which runs first. Idempotent; scoped to the 2026 election.',
    '',
    ...lines,
    '',
  ].join('\n');
}
